import { useEffect, useMemo, useState } from "react";
import { FileCheck2, LoaderCircle, Lock, Upload } from "lucide-react";

import { Banner, Field } from "@/components/ui-shell";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { SelectField } from "@/components/ui/select-field";
import { useLang } from "@/lib/i18n";

import {
  personnelApi,
  type PersonnelCategory,
  type PersonnelDocument,
  type PersonnelIntakeItem,
  type PersonnelProfileDocument,
} from "./api";
import {
  PERSONNEL_FILE_ACCEPT,
  formatDocumentPeriod,
  formatMonth,
  groupDocumentVersions,
  isArchiveTargetComplete,
  monthKeyOf,
  monthOptions,
  personnelMimeType,
  validatePersonnelFile,
  type ArchiveTarget,
} from "./model";
import { ArchiveName, PERSONNEL_TEXTAREA_CLASS, categoryLabel, errorMessage } from "./personnel-ui";

type EmployeeChoice = { id: string; display_name: string; is_active: boolean };

export type ArchiveDialogMode =
  | {
      kind: "upload";
      employeeId: string;
      /** Set for "upload correction": the new file becomes the next version of it. */
      supersedes?: PersonnelDocument | null;
    }
  | {
      kind: "intake";
      item: PersonnelIntakeItem;
      employees: readonly EmployeeChoice[];
    }
  | {
      kind: "profile";
      employeeId: string;
      /** A document on the linked interpreter profile, copied into the file. */
      document: PersonnelProfileDocument;
    };

// Paper archives are digitised back to the start of the retention periods.
const MONTHS_BACK = 120;
const PREVIEW_DEBOUNCE_MS = 300;

/**
 * Files a document into a personnel file: a new upload, a correction (new
 * version with a reason), a scan from the intake queue or a copy of a
 * document from the employee's interpreter profile. The archive name is
 * generated by the server and shown before saving.
 */
export function ArchiveDialog({
  open,
  mode,
  categories,
  onClose,
  onArchived,
}: {
  open: boolean;
  mode: ArchiveDialogMode | null;
  categories: readonly PersonnelCategory[];
  onClose: () => void;
  onArchived: (document: PersonnelDocument) => void;
}) {
  const { t } = useLang();
  const presetSupersedes = mode?.kind === "upload" ? mode.supersedes ?? null : null;
  // Identity of what is being filed; callers may pass a new mode object on every render.
  const modeKey =
    mode?.kind === "upload"
      ? `upload:${mode.employeeId}:${presetSupersedes?.id ?? ""}`
      : mode?.kind === "intake"
        ? `intake:${mode.item.id}`
        : mode
          ? `profile:${mode.employeeId}:${mode.document.document_id}`
          : "";
  const [employeeId, setEmployeeId] = useState("");
  const [category, setCategory] = useState("");
  const [period, setPeriod] = useState("");
  const [documentDate, setDocumentDate] = useState("");
  const [title, setTitle] = useState("");
  const [supersedesId, setSupersedesId] = useState("");
  const [reason, setReason] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [fileError, setFileError] = useState("");
  const [candidates, setCandidates] = useState<PersonnelDocument[]>([]);
  const [preview, setPreview] = useState<{ name: string; error: string } | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!open) return;
    setEmployeeId(mode?.kind === "upload" || mode?.kind === "profile" ? mode.employeeId : "");
    setCategory(
      mode?.kind === "profile" ? mode.document.suggested_category : presetSupersedes?.category ?? "",
    );
    setPeriod(monthKeyOf());
    setDocumentDate(mode?.kind === "profile" ? mode.document.document_date ?? "" : "");
    setTitle("");
    setSupersedesId(presetSupersedes?.id ?? "");
    setReason("");
    setFile(null);
    setFileError("");
    setCandidates([]);
    setPreview(null);
    setError("");
  }, [open, modeKey]);

  // Intake: documents of the chosen employee that a scan may correct.
  useEffect(() => {
    if (!open || mode?.kind !== "intake" || !employeeId) {
      setCandidates([]);
      return;
    }
    let cancelled = false;
    personnelApi
      .employee(employeeId)
      .then((file) => {
        if (!cancelled) setCandidates(file.documents.filter((document) => !document.deleted_at));
      })
      .catch(() => {
        if (!cancelled) setCandidates([]);
      });
    return () => {
      cancelled = true;
    };
  }, [open, modeKey, employeeId]);

  const selectedCategory = categories.find((entry) => entry.code === category);
  const target: ArchiveTarget = {
    category,
    period: selectedCategory?.monthly ? period : undefined,
    documentDate: selectedCategory && !selectedCategory.monthly ? documentDate : undefined,
    title,
    supersedesId: supersedesId || undefined,
    correctionReason: reason,
  };
  const mimeType =
    mode?.kind === "intake"
      ? mode.item.mime_type
      : mode?.kind === "profile"
        ? mode.document.mime_type ?? undefined
        : file
          ? personnelMimeType(file) ?? undefined
          : undefined;
  const targetComplete = Boolean(employeeId) && isArchiveTargetComplete(
    target,
    supersedesId ? true : selectedCategory?.monthly,
  );
  const previewKey = targetComplete
    ? `${employeeId}|${supersedesId || `${category}|${target.period ?? ""}|${target.documentDate ?? ""}`}|${mimeType ?? ""}`
    : "";

  useEffect(() => {
    if (!open || !previewKey) {
      setPreview(null);
      return;
    }
    let cancelled = false;
    const timer = window.setTimeout(() => {
      personnelApi
        .previewFileName(employeeId, target, mimeType)
        .then((result) => {
          if (!cancelled) setPreview({ name: result.file_name, error: "" });
        })
        .catch((reasonError: unknown) => {
          if (!cancelled) setPreview({ name: "", error: errorMessage(reasonError, t.common_failed_load) });
        });
    }, PREVIEW_DEBOUNCE_MS);
    return () => {
      cancelled = true;
      window.clearTimeout(timer);
    };
    // The key covers every input of the preview.
  }, [open, previewKey]);

  const correctionOptions = useMemo(
    () =>
      groupDocumentVersions(candidates).map((group) => ({
        value: group.current.id,
        label: `${categoryLabel(t, group.current.category, group.current.category_label)} · ${formatDocumentPeriod(group.current)} · ${group.current.archive_file_name}`,
      })),
    [candidates, t],
  );

  const monthChoices = useMemo(
    () => monthOptions(monthKeyOf(), MONTHS_BACK, 1).map((month) => ({ value: month, label: formatMonth(month) })),
    [],
  );

  const chooseFile = (next: File | null) => {
    setFile(next);
    const problem = next ? validatePersonnelFile(next) : null;
    setFileError(
      problem === "unsupported"
        ? t.personnel_file_unsupported
        : problem === "too_large"
          ? t.personnel_file_too_large
          : "",
    );
  };

  const needsFile = mode?.kind === "upload";
  const canSubmit =
    targetComplete && (!needsFile || (file && !fileError)) && !busy && !preview?.error;

  const submit = async () => {
    if (!mode || !canSubmit) return;
    setBusy(true);
    setError("");
    try {
      const document =
        mode.kind === "upload"
          ? await personnelApi.uploadDocument(employeeId, target, file as File)
          : mode.kind === "intake"
            ? await personnelApi.archiveIntake(mode.item.id, employeeId, target)
            : await personnelApi.importProfileDocument(employeeId, mode.document.document_id, target);
      onArchived(document);
      onClose();
    } catch (reasonError) {
      setError(errorMessage(reasonError, t.common_failed_create));
    } finally {
      setBusy(false);
    }
  };

  const isCorrection = Boolean(supersedesId);
  const dialogTitle =
    mode?.kind === "intake"
      ? t.personnel_intake_assign_title
      : mode?.kind === "profile"
        ? t.personnel_import_title
        : presetSupersedes
          ? t.personnel_correction_title
          : t.personnel_upload_title;
  const dirty = Boolean(file || title || reason || (mode?.kind === "intake" && employeeId));

  return (
    <Dialog open={open} onOpenChange={(next) => (!next ? onClose() : undefined)} dirty={dirty}>
      <DialogContent className="sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>{dialogTitle}</DialogTitle>
          <DialogDescription>
            {isCorrection ? t.personnel_correction_hint : t.personnel_upload_hint}
          </DialogDescription>
        </DialogHeader>

        <div className="grid gap-3">
          {mode?.kind === "intake" ? (
            <>
              <p className="text-xs text-muted-foreground">
                {t.personnel_intake_original_name}: <ArchiveName name={mode.item.original_file_name} />
              </p>
              <Field label={t.personnel_employee} required>
                <SelectField
                  value={employeeId}
                  aria-label={t.personnel_employee}
                  onValueChange={(value) => {
                    setEmployeeId(value);
                    setSupersedesId("");
                  }}
                  options={[
                    { value: "", label: t.common_select_placeholder, disabled: true },
                    ...mode.employees.map((employee) => ({
                      value: employee.id,
                      label: employee.is_active
                        ? employee.display_name
                        : `${employee.display_name} (${t.personnel_status_former})`,
                    })),
                  ]}
                />
              </Field>
              {employeeId && correctionOptions.length > 0 ? (
                <Field label={t.personnel_correction_of}>
                  <SelectField
                    value={supersedesId}
                    aria-label={t.personnel_correction_of}
                    onValueChange={setSupersedesId}
                    options={[{ value: "", label: t.personnel_correction_none }, ...correctionOptions]}
                  />
                </Field>
              ) : null}
            </>
          ) : null}

          {mode?.kind === "profile" ? (
            <p className="text-xs text-muted-foreground">
              {t.personnel_import_source}: <ArchiveName name={mode.document.original_file_name || mode.document.title} />
            </p>
          ) : null}

          {presetSupersedes ? (
            <div className="rounded-lg border border-border bg-muted/30 px-3 py-2 text-xs">
              <p className="font-medium text-foreground">{t.personnel_correction_of}</p>
              <ArchiveName name={presetSupersedes.archive_file_name} />
            </div>
          ) : null}

          {isCorrection ? (
            <Field label={t.personnel_correction_reason} required>
              <textarea
                className={PERSONNEL_TEXTAREA_CLASS}
                value={reason}
                maxLength={2000}
                onChange={(event) => setReason(event.target.value)}
              />
            </Field>
          ) : (
            <>
              <Field label={t.personnel_category} required>
                <SelectField
                  value={category}
                  aria-label={t.personnel_category}
                  onValueChange={setCategory}
                  options={[
                    { value: "", label: t.common_select_placeholder, disabled: true },
                    ...categories.map((entry) => ({
                      value: entry.code,
                      label: categoryLabel(t, entry.code, entry.file_label),
                    })),
                  ]}
                />
              </Field>
              {selectedCategory?.monthly ? (
                <Field label={t.personnel_period_month} required>
                  <SelectField
                    value={period}
                    aria-label={t.personnel_period_month}
                    onValueChange={setPeriod}
                    options={monthChoices}
                  />
                </Field>
              ) : selectedCategory ? (
                <Field label={t.personnel_document_date} htmlFor="personnel-document-date" required>
                  <Input
                    id="personnel-document-date"
                    type="date"
                    value={documentDate}
                    onChange={(event) => setDocumentDate(event.target.value)}
                  />
                </Field>
              ) : null}
            </>
          )}

          <Field label={t.personnel_title_optional} htmlFor="personnel-document-title">
            <Input
              id="personnel-document-title"
              value={title}
              maxLength={200}
              onChange={(event) => setTitle(event.target.value)}
            />
          </Field>

          {needsFile ? (
            <Field label={t.personnel_file} htmlFor="personnel-document-file" required>
              <label className="flex cursor-pointer items-center gap-2 rounded-lg border border-dashed border-border px-3 py-3 text-sm hover:bg-muted/30">
                <Upload className="size-4 text-muted-foreground" />
                <span className="min-w-0 truncate">{file ? file.name : t.personnel_choose_file}</span>
                <input
                  id="personnel-document-file"
                  type="file"
                  className="sr-only"
                  accept={PERSONNEL_FILE_ACCEPT}
                  onChange={(event) => chooseFile(event.target.files?.[0] ?? null)}
                />
              </label>
              <p className="text-xs text-muted-foreground">{t.personnel_file_hint}</p>
              {fileError ? <p className="text-xs text-destructive">{fileError}</p> : null}
            </Field>
          ) : null}

          <div className="rounded-lg border border-emerald-200 bg-emerald-50/60 px-3 py-2 text-xs text-emerald-900">
            <p className="flex items-center gap-1.5 font-medium">
              <FileCheck2 className="size-3.5" />
              {t.personnel_will_be_archived_as}
            </p>
            {preview?.name ? (
              <ArchiveName name={preview.name} className="text-emerald-950" />
            ) : preview?.error ? (
              <p className="text-destructive">{preview.error}</p>
            ) : (
              <p className="text-emerald-900/70">{t.personnel_archive_name_pending}</p>
            )}
            <p className="mt-1 flex items-center gap-1.5 text-emerald-900/80">
              <Lock className="size-3" />
              {t.personnel_immutable_hint}
            </p>
          </div>
        </div>

        {error ? <Banner tone="error">{error}</Banner> : null}
        <DialogFooter>
          <Button type="button" variant="outline" onClick={onClose} disabled={busy}>
            {t.common_cancel}
          </Button>
          <Button type="button" onClick={() => void submit()} disabled={!canSubmit}>
            {busy ? <LoaderCircle className="animate-spin" /> : null}
            {t.personnel_archive_action}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
