-- Complete the medical document specialty catalogue used by upload, edit,
-- classification and background OCR naming.
INSERT INTO ref_document_categories (
    id,
    parent_id,
    level,
    name_de,
    name_en,
    is_medical,
    description,
    portal_group,
    sort_order,
    patient_visible,
    short_code,
    access_category,
    aliases
) VALUES
    ('medical_gastro', 'medical', 'subcategory', 'Gastroenterologie', 'Gastroenterology', true, 'Unterlagen aus der Gastroenterologie.', 'medical_report', 401, true, 'GASTRO', 'medical', ARRAY['gastro', 'gastroenterologie']::TEXT[]),
    ('medical_onko', 'medical', 'subcategory', 'Onkologie', 'Oncology', true, 'Unterlagen aus der Onkologie.', 'medical_report', 402, true, 'ONKO', 'medical', ARRAY['onko', 'onkologie', 'oncology']::TEXT[]),
    ('medical_kardio', 'medical', 'subcategory', 'Kardiologie', 'Cardiology', true, 'Unterlagen aus der Kardiologie.', 'medical_report', 403, true, 'KARDIO', 'medical', ARRAY['kardio', 'kardiologie', 'cardiology']::TEXT[]),
    ('medical_kardch', 'medical', 'subcategory', 'Kardiochirurgie', 'Cardiac surgery', true, 'Unterlagen aus der Kardiochirurgie.', 'medical_report', 404, true, 'KARDCH', 'medical', ARRAY['kardch', 'kardiochirurgie', 'cardiac surgery']::TEXT[]),
    ('medical_derma', 'medical', 'subcategory', 'Dermatologie', 'Dermatology', true, 'Unterlagen aus der Dermatologie.', 'medical_report', 405, true, 'DERMA', 'medical', ARRAY['derma', 'dermatologie', 'dermatology']::TEXT[]),
    ('medical_dermch', 'medical', 'subcategory', 'Dermatologische Chirurgie', 'Dermatologic surgery', true, 'Unterlagen aus der dermatologischen Chirurgie.', 'medical_report', 406, true, 'DERMCH', 'medical', ARRAY['dermch', 'dermatochirurgie', 'dermatologic surgery']::TEXT[]),
    ('medical_radiology', 'medical', 'subcategory', 'Radiologie', 'Radiology', true, 'Radiologie-Unterlagen (CT, MRT, PET-CT usw.).', 'medical_report', 407, true, 'RAD', 'medical', ARRAY['rad', 'radiologie', 'radiology', 'ct', 'mrt', 'pet-ct']::TEXT[]),
    ('medical_lab', 'medical', 'subcategory', 'Labor', 'Laboratory', true, 'Laborbefunde und Laborergebnisse.', 'lab_analysis', 408, true, 'LAB', 'medical', ARRAY['lab', 'labor', 'laborbefund']::TEXT[]),
    ('medical_patho_histo', 'medical', 'subcategory', 'Histologie / Pathologie', 'Histology / pathology', true, 'Histologische und pathologische Befunde.', 'lab_analysis', 409, true, 'HISTO/PATHO', 'medical', ARRAY['histo', 'patho', 'histologie', 'pathologie']::TEXT[]),
    ('medical_neuro', 'medical', 'subcategory', 'Neurologie', 'Neurology', true, 'Unterlagen aus der Neurologie.', 'medical_report', 410, true, 'NEURO', 'medical', ARRAY['neuro', 'neurologie', 'neurology']::TEXT[]),
    ('medical_neurch', 'medical', 'subcategory', 'Neurochirurgie', 'Neurosurgery', true, 'Unterlagen aus der Neurochirurgie.', 'medical_report', 411, true, 'NEURCH', 'medical', ARRAY['neurch', 'neurochirurgie', 'neurosurgery']::TEXT[]),
    ('medical_chir', 'medical', 'subcategory', 'Chirurgie', 'Surgery', true, 'Unterlagen aus der Chirurgie.', 'medical_report', 412, true, 'CHIR', 'medical', ARRAY['chir', 'chirurgie', 'surgery']::TEXT[]),
    ('medical_gyn', 'medical', 'subcategory', 'Gynäkologie', 'Gynecology', true, 'Unterlagen aus der Gynäkologie.', 'medical_report', 413, true, 'GYN', 'medical', ARRAY['gyn', 'gynäkologie', 'gynecology']::TEXT[]),
    ('medical_gynch', 'medical', 'subcategory', 'Gynäkologische Chirurgie', 'Gynecologic surgery', true, 'Unterlagen aus der gynäkologischen Chirurgie.', 'medical_report', 414, true, 'GYNCH', 'medical', ARRAY['gynch', 'gynäkologische chirurgie', 'gynecologic surgery']::TEXT[]),
    ('medical_auge', 'medical', 'subcategory', 'Ophthalmologie', 'Ophthalmology', true, 'Unterlagen aus der Ophthalmologie.', 'medical_report', 415, true, 'AUGE', 'medical', ARRAY['auge', 'augenheilkunde', 'ophthalmologie']::TEXT[]),
    ('medical_augch', 'medical', 'subcategory', 'Ophthalmologische Chirurgie', 'Ophthalmic surgery', true, 'Unterlagen aus der ophthalmologischen Chirurgie.', 'medical_report', 416, true, 'AUGCH', 'medical', ARRAY['augch', 'augenchirurgie', 'ophthalmic surgery']::TEXT[]),
    ('medical_hamat', 'medical', 'subcategory', 'Hämatologie', 'Hematology', true, 'Unterlagen aus der Hämatologie.', 'medical_report', 417, true, 'HÄMAT', 'medical', ARRAY['hämat', 'hämatologie', 'haematologie', 'hematology']::TEXT[]),
    ('medical_uro', 'medical', 'subcategory', 'Urologie', 'Urology', true, 'Unterlagen aus der Urologie.', 'medical_report', 418, true, 'URO', 'medical', ARRAY['uro', 'urologie', 'urology']::TEXT[]),
    ('medical_uroch', 'medical', 'subcategory', 'Urologische Chirurgie', 'Urologic surgery', true, 'Unterlagen aus der urologischen Chirurgie.', 'medical_report', 419, true, 'UROCH', 'medical', ARRAY['uroch', 'urologische chirurgie', 'urologic surgery']::TEXT[]),
    ('medical_schlaf', 'medical', 'subcategory', 'Schlafmedizin', 'Sleep medicine', true, 'Unterlagen aus dem Schlaflabor und der Schlafmedizin.', 'medical_report', 420, true, 'SCHLAF', 'medical', ARRAY['schlaf', 'schlaflabor', 'schlafmedizin']::TEXT[]),
    ('medical_endo', 'medical', 'subcategory', 'Endokrinologie', 'Endocrinology', true, 'Unterlagen aus der Endokrinologie.', 'medical_report', 421, true, 'ENDO', 'medical', ARRAY['endo', 'endokrinologie', 'endocrinology']::TEXT[]),
    ('medical_endoch', 'medical', 'subcategory', 'Endokrine Chirurgie', 'Endocrine surgery', true, 'Unterlagen aus der endokrinen Chirurgie.', 'medical_report', 422, true, 'ENDOCH', 'medical', ARRAY['endoch', 'endokrine chirurgie', 'endocrine surgery']::TEXT[]),
    ('medical_vask', 'medical', 'subcategory', 'Gefäßchirurgie', 'Vascular surgery', true, 'Unterlagen aus der Gefäßchirurgie.', 'medical_report', 423, true, 'VASK', 'medical', ARRAY['vask', 'gefäßchirurgie', 'vascular surgery']::TEXT[]),
    ('medical_orthol', 'medical', 'subcategory', 'Orthopädie', 'Orthopedics', true, 'Unterlagen aus der Orthopädie.', 'medical_report', 424, true, 'ORTHOL', 'medical', ARRAY['orthol', 'orthopädie', 'orthopedics']::TEXT[]),
    ('medical_unfal', 'medical', 'subcategory', 'Unfallchirurgie', 'Trauma surgery', true, 'Unterlagen aus der Unfallchirurgie.', 'medical_report', 425, true, 'UNFAL', 'medical', ARRAY['unfal', 'unfallchirurgie', 'trauma surgery']::TEXT[]),
    ('medical_mkg', 'medical', 'subcategory', 'Mund-Kiefer-Gesichtschirurgie', 'Oral and maxillofacial surgery', true, 'Unterlagen aus der Mund-Kiefer-Gesichtschirurgie.', 'medical_report', 426, true, 'MKG', 'medical', ARRAY['mkg', 'mund-kiefer-gesichtschirurgie', 'maxillofacial']::TEXT[]),
    ('medical_dent', 'medical', 'subcategory', 'Zahnmedizin', 'Dentistry', true, 'Unterlagen vom Zahnarzt.', 'medical_report', 427, true, 'DENT', 'medical', ARRAY['dent', 'zahnarzt', 'zahnmedizin', 'dentistry']::TEXT[]),
    ('medical_kfo', 'medical', 'subcategory', 'Kieferorthopädie', 'Orthodontics', true, 'Unterlagen aus der Kieferorthopädie.', 'medical_report', 428, true, 'KFO', 'medical', ARRAY['kfo', 'kieferorthopädie', 'orthodontics']::TEXT[]),
    ('medical_plastchir', 'medical', 'subcategory', 'Plastische Chirurgie', 'Plastic surgery', true, 'Unterlagen aus der plastischen Chirurgie.', 'medical_report', 429, true, 'PLASTCHIR', 'medical', ARRAY['plastchir', 'plastische chirurgie', 'plastic surgery']::TEXT[]),
    ('medical_pad', 'medical', 'subcategory', 'Kinderheilkunde', 'Pediatrics', true, 'Unterlagen aus der Kinderheilkunde.', 'medical_report', 430, true, 'PÄD', 'medical', ARRAY['päd', 'pädiatrie', 'kinderheilkunde', 'pediatrics']::TEXT[]),
    ('medical_physio_reha', 'medical', 'subcategory', 'Physiotherapie / Rehabilitation', 'Physiotherapy / rehabilitation', true, 'Unterlagen aus der Physiotherapie und Rehabilitation.', 'medical_report', 431, true, 'PHYSIO/REHA', 'medical', ARRAY['physio', 'reha', 'physiotherapie', 'rehabilitation']::TEXT[]),
    ('medical_hno', 'medical', 'subcategory', 'Hals-Nasen-Ohren-Heilkunde', 'Otorhinolaryngology', true, 'Unterlagen aus der Hals-Nasen-Ohren-Heilkunde.', 'medical_report', 432, true, 'HNO', 'medical', ARRAY['hno', 'hals-nasen-ohren', 'otorhinolaryngology']::TEXT[]),
    ('medical_infekt', 'medical', 'subcategory', 'Infektiologie', 'Infectious diseases', true, 'Unterlagen aus der Infektiologie.', 'medical_report', 433, true, 'INFEKT', 'medical', ARRAY['infekt', 'infektiologie', 'infectious diseases']::TEXT[]),
    ('medical_ana', 'medical', 'subcategory', 'Anästhesie', 'Anesthesiology', true, 'Unterlagen aus der Anästhesie.', 'medical_report', 434, true, 'ANA', 'medical', ARRAY['ana', 'anästhesie', 'anaesthesiology', 'anesthesiology']::TEXT[]),
    ('medical_nephro', 'medical', 'subcategory', 'Nephrologie', 'Nephrology', true, 'Unterlagen aus der Nephrologie.', 'medical_report', 435, true, 'NEPHRO', 'medical', ARRAY['nephro', 'nephrologie', 'nephrology']::TEXT[]),
    ('medical_psych', 'medical', 'subcategory', 'Psychiatrie', 'Psychiatry', true, 'Unterlagen aus der Psychiatrie.', 'medical_report', 436, true, 'PSYCH', 'medical', ARRAY['psych', 'psychiatrie', 'psychiatry']::TEXT[]),
    ('medical_pneumo_resp', 'medical', 'subcategory', 'Pneumologie', 'Pulmonology', true, 'Unterlagen aus der Pneumologie.', 'medical_report', 437, true, 'PNEUMO/RESP', 'medical', ARRAY['pneumo', 'resp', 'pneumologie', 'lungenarzt', 'pulmonology']::TEXT[]),
    ('medical_prokto', 'medical', 'subcategory', 'Proktologie', 'Proctology', true, 'Unterlagen aus der Proktologie.', 'medical_report', 438, true, 'PROKTO', 'medical', ARRAY['prokto', 'proktologie', 'proctology']::TEXT[]),
    ('medical_rheum', 'medical', 'subcategory', 'Rheumatologie', 'Rheumatology', true, 'Unterlagen aus der Rheumatologie.', 'medical_report', 439, true, 'RHEUM', 'medical', ARRAY['rheum', 'rheumatologie', 'rheumatology']::TEXT[]),
    ('medical_ger', 'medical', 'subcategory', 'Geriatrie', 'Geriatrics', true, 'Unterlagen aus der Geriatrie.', 'medical_report', 440, true, 'GER', 'medical', ARRAY['ger', 'geriatrie', 'geriatrics']::TEXT[]),
    ('medical_allmed', 'medical', 'subcategory', 'Allgemeinmedizin', 'General medicine', true, 'Unterlagen aus der Allgemeinmedizin.', 'medical_report', 441, true, 'ALLMED', 'medical', ARRAY['allmed', 'allgemeinmedizin', 'hausarzt', 'general medicine']::TEXT[])
ON CONFLICT (id) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    level = EXCLUDED.level,
    name_de = EXCLUDED.name_de,
    name_en = EXCLUDED.name_en,
    is_medical = EXCLUDED.is_medical,
    description = EXCLUDED.description,
    portal_group = EXCLUDED.portal_group,
    sort_order = EXCLUDED.sort_order,
    patient_visible = EXCLUDED.patient_visible,
    short_code = EXCLUDED.short_code,
    access_category = EXCLUDED.access_category,
    aliases = EXCLUDED.aliases;
