-- Canonical DE/RU medical specialization directory from CRM task.
-- German labels are ordered alphabetically through sort_order.

INSERT INTO medical_specializations (code, name_en, name_de, name_ru, is_active, sort_order)
VALUES
    ('allgemeinchirurgie', 'Allgemeinchirurgie', 'Allgemeinchirurgie', 'Общая хирургия', TRUE, 100),
    ('allgemeinmedizin', 'Allgemeinmedizin', 'Allgemeinmedizin', 'Общая медицина', TRUE, 110),
    ('anaesthesiologie', 'Anästhesiologie', 'Anästhesiologie', 'Анестезиология', TRUE, 120),
    ('anatomie', 'Anatomie', 'Anatomie', 'Анатомия', TRUE, 130),
    ('angiologie', 'Angiologie', 'Angiologie', 'Ангиология', TRUE, 140),
    ('arbeitsmedizin', 'Arbeitsmedizin', 'Arbeitsmedizin', 'Медицина труда', TRUE, 150),
    ('augenheilkunde', 'Augenheilkunde', 'Augenheilkunde', 'Офтальмология', TRUE, 160),
    ('biochemie', 'Biochemie', 'Biochemie', 'Биохимия', TRUE, 170),
    ('chirurgie', 'Chirurgie', 'Chirurgie', 'Хирургия', TRUE, 180),
    ('dermatologie_und_venerologie', 'Dermatologie und Venerologie', 'Dermatologie und Venerologie', 'Дерматовенерология', TRUE, 190),
    ('endokrinologie_und_diabetologie', 'Endokrinologie und Diabetologie', 'Endokrinologie und Diabetologie', 'Эндокринология и диабетология', TRUE, 200),
    ('forensische_psychiatrie', 'Forensische Psychiatrie', 'Forensische Psychiatrie', 'Судебная психиатрия', TRUE, 210),
    ('gastroenterologie', 'Gastroenterologie', 'Gastroenterologie', 'Гастроэнтерология', TRUE, 220),
    ('gefaesschirurgie', 'Gefäßchirurgie', 'Gefäßchirurgie', 'Сосудистая хирургия', TRUE, 230),
    ('geriatrie', 'Geriatrie', 'Geriatrie', 'Гериатрия', TRUE, 240),
    ('gynaekologie_und_geburtshilfe', 'Gynäkologie und Geburtshilfe', 'Gynäkologie und Geburtshilfe', 'Акушерство и гинекология', TRUE, 250),
    ('gynaekologische_endokrinologie_und_reproduktionsmedizin', 'Gynäkologische Endokrinologie und Reproduktionsmedizin', 'Gynäkologische Endokrinologie und Reproduktionsmedizin', 'Гинекологическая эндокринология и репродуктивная медицина', TRUE, 260),
    ('gynaekologische_onkologie', 'Gynäkologische Onkologie', 'Gynäkologische Onkologie', 'Гинекологическая онкология', TRUE, 270),
    ('haematologie_und_onkologie', 'Hämatologie und Onkologie', 'Hämatologie und Onkologie', 'Гематология и онкология', TRUE, 280),
    ('hals_nasen_ohrenheilkunde', 'Hals-Nasen-Ohrenheilkunde', 'Hals-Nasen-Ohrenheilkunde', 'Оториноларингология', TRUE, 290),
    ('herzchirurgie', 'Herzchirurgie', 'Herzchirurgie', 'Кардиохирургия', TRUE, 300),
    ('humangenetik', 'Humangenetik', 'Humangenetik', 'Медицинская генетика', TRUE, 310),
    ('hygiene_und_umweltmedizin', 'Hygiene und Umweltmedizin', 'Hygiene und Umweltmedizin', 'Гигиена и экологическая медицина', TRUE, 320),
    ('innere_medizin', 'Innere Medizin', 'Innere Medizin', 'Внутренние болезни', TRUE, 330),
    ('kardiologie', 'Kardiologie', 'Kardiologie', 'Кардиология', TRUE, 340),
    ('kinder_haematologie_und_onkologie', 'Kinder-Hämatologie und -Onkologie', 'Kinder-Hämatologie und -Onkologie', 'Детская гематология и онкология', TRUE, 350),
    ('kinder_kardiologie', 'Kinder-Kardiologie', 'Kinder-Kardiologie', 'Детская кардиология', TRUE, 360),
    ('kinder_und_jugendmedizin', 'Kinder- und Jugendmedizin', 'Kinder- und Jugendmedizin', 'Педиатрия', TRUE, 370),
    ('kinder_und_jugendpsychiatrie_und_psychotherapie', 'Kinder- und Jugendpsychiatrie und -psychotherapie', 'Kinder- und Jugendpsychiatrie und -psychotherapie', 'Детская и подростковая психиатрия и психотерапия', TRUE, 380),
    ('kinderchirurgie', 'Kinderchirurgie', 'Kinderchirurgie', 'Детская хирургия', TRUE, 390),
    ('kinderradiologie', 'Kinderradiologie', 'Kinderradiologie', 'Детская радиология', TRUE, 400),
    ('klinische_pharmakologie', 'Klinische Pharmakologie', 'Klinische Pharmakologie', 'Клиническая фармакология', TRUE, 410),
    ('laboratoriumsmedizin', 'Laboratoriumsmedizin', 'Laboratoriumsmedizin', 'Лабораторная медицина', TRUE, 420),
    ('mikrobiologie_virologie_und_infektionsepidemiologie', 'Mikrobiologie, Virologie und Infektionsepidemiologie', 'Mikrobiologie, Virologie und Infektionsepidemiologie', 'Микробиология, вирусология и инфекционная эпидемиология', TRUE, 430),
    ('mund_kiefer_gesichtschirurgie', 'Mund-Kiefer-Gesichtschirurgie', 'Mund-Kiefer-Gesichtschirurgie', 'Челюстно-лицевая хирургия', TRUE, 440),
    ('neonatologie', 'Neonatologie', 'Neonatologie', 'Неонатология', TRUE, 450),
    ('nephrologie', 'Nephrologie', 'Nephrologie', 'Нефрология', TRUE, 460),
    ('neurochirurgie', 'Neurochirurgie', 'Neurochirurgie', 'Нейрохирургия', TRUE, 470),
    ('neurologie', 'Neurologie', 'Neurologie', 'Неврология', TRUE, 480),
    ('neuropaediatrie', 'Neuropädiatrie', 'Neuropädiatrie', 'Нейропедиатрия', TRUE, 490),
    ('neuropathologie', 'Neuropathologie', 'Neuropathologie', 'Нейропатология', TRUE, 500),
    ('neuroradiologie', 'Neuroradiologie', 'Neuroradiologie', 'Нейрорадиология', TRUE, 510),
    ('nuklearmedizin', 'Nuklearmedizin', 'Nuklearmedizin', 'Ядерная медицина', TRUE, 520),
    ('oeffentliches_gesundheitswesen', 'Öffentliches Gesundheitswesen', 'Öffentliches Gesundheitswesen', 'Общественное здравоохранение', TRUE, 530),
    ('orthopaedie_und_unfallchirurgie', 'Orthopädie und Unfallchirurgie', 'Orthopädie und Unfallchirurgie', 'Ортопедия и травматология', TRUE, 540),
    ('pathologie', 'Pathologie', 'Pathologie', 'Патология', TRUE, 550),
    ('pharmakologie', 'Pharmakologie', 'Pharmakologie', 'Фармакология', TRUE, 560),
    ('pharmakologie_und_toxikologie', 'Pharmakologie und Toxikologie', 'Pharmakologie und Toxikologie', 'Фармакология и токсикология', TRUE, 570),
    ('phoniatrie_und_paedaudiologie', 'Phoniatrie und Pädaudiologie', 'Phoniatrie und Pädaudiologie', 'Фониатрия и педиатрическая аудиология', TRUE, 580),
    ('physikalische_und_rehabilitative_medizin', 'Physikalische und Rehabilitative Medizin', 'Physikalische und Rehabilitative Medizin', 'Физическая и реабилитационная медицина', TRUE, 590),
    ('physiologie', 'Physiologie', 'Physiologie', 'Физиология', TRUE, 600),
    ('plastische_und_aesthetische_chirurgie', 'Plastische und Ästhetische Chirurgie', 'Plastische und Ästhetische Chirurgie', 'Пластическая и эстетическая хирургия', TRUE, 610),
    ('pneumologie', 'Pneumologie', 'Pneumologie', 'Пульмонология', TRUE, 620),
    ('psychiatrie_und_psychotherapie', 'Psychiatrie und Psychotherapie', 'Psychiatrie und Psychotherapie', 'Психиатрия и психотерапия', TRUE, 630),
    ('psychosomatische_medizin_und_psychotherapie', 'Psychosomatische Medizin und Psychotherapie', 'Psychosomatische Medizin und Psychotherapie', 'Психосоматическая медицина и психотерапия', TRUE, 640),
    ('radiologie', 'Radiologie', 'Radiologie', 'Радиология', TRUE, 650),
    ('rechtsmedizin', 'Rechtsmedizin', 'Rechtsmedizin', 'Судебная медицина', TRUE, 660),
    ('rheumatologie', 'Rheumatologie', 'Rheumatologie', 'Ревматология', TRUE, 670),
    ('spezielle_geburtshilfe_und_perinatalmedizin', 'Spezielle Geburtshilfe und Perinatalmedizin', 'Spezielle Geburtshilfe und Perinatalmedizin', 'Специальное акушерство и перинатология', TRUE, 680),
    ('sportmedizin', 'Sportmedizin', 'Sportmedizin', 'Спортивная медицина', TRUE, 690),
    ('strahlentherapie', 'Strahlentherapie', 'Strahlentherapie', 'Лучевая терапия', TRUE, 700),
    ('thoraxchirurgie', 'Thoraxchirurgie', 'Thoraxchirurgie', 'Торакальная хирургия', TRUE, 710),
    ('transfusionsmedizin', 'Transfusionsmedizin', 'Transfusionsmedizin', 'Трансфузиология', TRUE, 720),
    ('urologie', 'Urologie', 'Urologie', 'Урология', TRUE, 730),
    ('viszeralchirurgie', 'Viszeralchirurgie', 'Viszeralchirurgie', 'Висцеральная хирургия', TRUE, 740)
ON CONFLICT (code) DO UPDATE
SET name_en = EXCLUDED.name_en,
    name_de = EXCLUDED.name_de,
    name_ru = EXCLUDED.name_ru,
    is_active = TRUE,
    sort_order = EXCLUDED.sort_order,
    deleted_at = NULL,
    updated_at = now();

UPDATE medical_specializations
SET is_active = FALSE,
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE code IN (
    'allergology',
    'anesthesiology',
    'cardiology',
    'dermatology',
    'endocrinology',
    'gastroenterology',
    'gynecology',
    'hematology',
    'internal_medicine',
    'neurology',
    'oncology',
    'orthopedics',
    'pediatrics',
    'psychiatry',
    'radiology',
    'surgery',
    'urology'
);

UPDATE medical_specializations
SET sort_order = GREATEST(sort_order, 900)
WHERE code NOT IN (
    'allgemeinchirurgie',
    'allgemeinmedizin',
    'anaesthesiologie',
    'anatomie',
    'angiologie',
    'arbeitsmedizin',
    'augenheilkunde',
    'biochemie',
    'chirurgie',
    'dermatologie_und_venerologie',
    'endokrinologie_und_diabetologie',
    'forensische_psychiatrie',
    'gastroenterologie',
    'gefaesschirurgie',
    'geriatrie',
    'gynaekologie_und_geburtshilfe',
    'gynaekologische_endokrinologie_und_reproduktionsmedizin',
    'gynaekologische_onkologie',
    'haematologie_und_onkologie',
    'hals_nasen_ohrenheilkunde',
    'herzchirurgie',
    'humangenetik',
    'hygiene_und_umweltmedizin',
    'innere_medizin',
    'kardiologie',
    'kinder_haematologie_und_onkologie',
    'kinder_kardiologie',
    'kinder_und_jugendmedizin',
    'kinder_und_jugendpsychiatrie_und_psychotherapie',
    'kinderchirurgie',
    'kinderradiologie',
    'klinische_pharmakologie',
    'laboratoriumsmedizin',
    'mikrobiologie_virologie_und_infektionsepidemiologie',
    'mund_kiefer_gesichtschirurgie',
    'neonatologie',
    'nephrologie',
    'neurochirurgie',
    'neurologie',
    'neuropaediatrie',
    'neuropathologie',
    'neuroradiologie',
    'nuklearmedizin',
    'oeffentliches_gesundheitswesen',
    'orthopaedie_und_unfallchirurgie',
    'pathologie',
    'pharmakologie',
    'pharmakologie_und_toxikologie',
    'phoniatrie_und_paedaudiologie',
    'physikalische_und_rehabilitative_medizin',
    'physiologie',
    'plastische_und_aesthetische_chirurgie',
    'pneumologie',
    'psychiatrie_und_psychotherapie',
    'psychosomatische_medizin_und_psychotherapie',
    'radiologie',
    'rechtsmedizin',
    'rheumatologie',
    'spezielle_geburtshilfe_und_perinatalmedizin',
    'sportmedizin',
    'strahlentherapie',
    'thoraxchirurgie',
    'transfusionsmedizin',
    'urologie',
    'viszeralchirurgie'
)
AND sort_order < 900;
