CREATE TABLE field_access_policies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    role TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    field_name TEXT NOT NULL,
    access_level TEXT NOT NULL CHECK (access_level IN ('full', 'masked', 'hidden', 'conditional')),
    condition_type TEXT CHECK (condition_type IN ('assigned_appointment', 'freigegeben', 'own_data') OR condition_type IS NULL),
    is_system_locked BOOLEAN NOT NULL DEFAULT false,
    updated_by UUID REFERENCES users(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(role, entity_type, field_name)
);

CREATE INDEX idx_fap_role_entity ON field_access_policies(role, entity_type);

CREATE TABLE record_access_overrides (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    entity_type TEXT NOT NULL,
    entity_id UUID NOT NULL,
    target_role TEXT,
    target_user_id UUID REFERENCES users(id),
    field_name TEXT,
    access_level TEXT NOT NULL CHECK (access_level IN ('full', 'hidden')),
    reason TEXT,
    granted_by UUID NOT NULL REFERENCES users(id),
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at TIMESTAMPTZ
);

CREATE INDEX idx_rao_entity ON record_access_overrides(entity_type, entity_id);
CREATE INDEX idx_rao_target ON record_access_overrides(target_role, target_user_id);

INSERT INTO field_access_policies (role, entity_type, field_name, access_level, condition_type, is_system_locked) VALUES
('patient_manager', 'patient', 'name', 'full', NULL, false),
('patient_manager', 'patient', 'birth_date', 'full', NULL, false),
('patient_manager', 'patient', 'phone', 'full', NULL, false),
('patient_manager', 'patient', 'email', 'full', NULL, false),
('patient_manager', 'patient', 'nationality', 'full', NULL, false),
('patient_manager', 'patient', 'languages', 'full', NULL, false),
('patient_manager', 'patient', 'insurance', 'full', NULL, false),
('patient_manager', 'patient', 'diagnosis', 'full', NULL, false),
('patient_manager', 'patient', 'medications', 'full', NULL, false),
('patient_manager', 'patient', 'allergies', 'full', NULL, false),
('patient_manager', 'patient', 'vitals', 'full', NULL, false),
('patient_manager', 'patient', 'internal_notes', 'full', NULL, false),
('patient_manager', 'patient', 'travel_data', 'full', NULL, false),

('teamlead_interpreter', 'patient', 'name', 'full', NULL, false),
('teamlead_interpreter', 'patient', 'birth_date', 'full', NULL, false),
('teamlead_interpreter', 'patient', 'phone', 'full', NULL, false),
('teamlead_interpreter', 'patient', 'email', 'full', NULL, false),
('teamlead_interpreter', 'patient', 'nationality', 'full', NULL, false),
('teamlead_interpreter', 'patient', 'languages', 'full', NULL, false),
('teamlead_interpreter', 'patient', 'insurance', 'hidden', NULL, false),
('teamlead_interpreter', 'patient', 'diagnosis', 'hidden', NULL, false),
('teamlead_interpreter', 'patient', 'medications', 'hidden', NULL, false),
('teamlead_interpreter', 'patient', 'allergies', 'hidden', NULL, false),
('teamlead_interpreter', 'patient', 'vitals', 'hidden', NULL, false),
('teamlead_interpreter', 'patient', 'internal_notes', 'hidden', NULL, false),
('teamlead_interpreter', 'patient', 'travel_data', 'full', NULL, false),

('interpreter', 'patient', 'name', 'full', NULL, false),
('interpreter', 'patient', 'birth_date', 'full', NULL, false),
('interpreter', 'patient', 'phone', 'full', NULL, false),
('interpreter', 'patient', 'email', 'masked', NULL, false),
('interpreter', 'patient', 'nationality', 'full', NULL, false),
('interpreter', 'patient', 'languages', 'full', NULL, false),
('interpreter', 'patient', 'insurance', 'hidden', NULL, false),
('interpreter', 'patient', 'diagnosis', 'conditional', 'assigned_appointment', false),
('interpreter', 'patient', 'medications', 'conditional', 'assigned_appointment', false),
('interpreter', 'patient', 'allergies', 'conditional', 'assigned_appointment', false),
('interpreter', 'patient', 'vitals', 'hidden', NULL, false),
('interpreter', 'patient', 'internal_notes', 'hidden', NULL, false),
('interpreter', 'patient', 'travel_data', 'hidden', NULL, false),

('concierge', 'patient', 'name', 'full', NULL, false),
('concierge', 'patient', 'birth_date', 'full', NULL, false),
('concierge', 'patient', 'phone', 'full', NULL, false),
('concierge', 'patient', 'email', 'full', NULL, false),
('concierge', 'patient', 'nationality', 'full', NULL, false),
('concierge', 'patient', 'languages', 'full', NULL, false),
('concierge', 'patient', 'insurance', 'hidden', NULL, false),
('concierge', 'patient', 'diagnosis', 'hidden', NULL, true),
('concierge', 'patient', 'medications', 'hidden', NULL, true),
('concierge', 'patient', 'allergies', 'hidden', NULL, true),
('concierge', 'patient', 'vitals', 'hidden', NULL, true),
('concierge', 'patient', 'internal_notes', 'hidden', NULL, false),
('concierge', 'patient', 'travel_data', 'full', NULL, false),

('billing', 'patient', 'name', 'full', NULL, false),
('billing', 'patient', 'birth_date', 'full', NULL, false),
('billing', 'patient', 'phone', 'full', NULL, false),
('billing', 'patient', 'email', 'full', NULL, false),
('billing', 'patient', 'nationality', 'full', NULL, false),
('billing', 'patient', 'languages', 'hidden', NULL, false),
('billing', 'patient', 'insurance', 'full', NULL, false),
('billing', 'patient', 'diagnosis', 'hidden', NULL, true),
('billing', 'patient', 'medications', 'hidden', NULL, true),
('billing', 'patient', 'allergies', 'hidden', NULL, true),
('billing', 'patient', 'vitals', 'hidden', NULL, true),
('billing', 'patient', 'internal_notes', 'hidden', NULL, false),
('billing', 'patient', 'travel_data', 'hidden', NULL, false),

('sales', 'patient', 'name', 'hidden', NULL, false),
('sales', 'patient', 'birth_date', 'hidden', NULL, false),
('sales', 'patient', 'phone', 'hidden', NULL, false),
('sales', 'patient', 'email', 'hidden', NULL, false),
('sales', 'patient', 'nationality', 'hidden', NULL, false),
('sales', 'patient', 'languages', 'hidden', NULL, false),
('sales', 'patient', 'insurance', 'hidden', NULL, false),
('sales', 'patient', 'diagnosis', 'hidden', NULL, true),
('sales', 'patient', 'medications', 'hidden', NULL, true),
('sales', 'patient', 'allergies', 'hidden', NULL, true),
('sales', 'patient', 'vitals', 'hidden', NULL, true),
('sales', 'patient', 'internal_notes', 'hidden', NULL, false),
('sales', 'patient', 'travel_data', 'hidden', NULL, false),

('patient', 'patient', 'name', 'conditional', 'freigegeben', false),
('patient', 'patient', 'birth_date', 'conditional', 'freigegeben', false),
('patient', 'patient', 'phone', 'conditional', 'freigegeben', false),
('patient', 'patient', 'email', 'conditional', 'freigegeben', false),
('patient', 'patient', 'nationality', 'conditional', 'freigegeben', false),
('patient', 'patient', 'languages', 'conditional', 'freigegeben', false),
('patient', 'patient', 'insurance', 'conditional', 'freigegeben', false),
('patient', 'patient', 'diagnosis', 'conditional', 'freigegeben', false),
('patient', 'patient', 'medications', 'conditional', 'freigegeben', false),
('patient', 'patient', 'allergies', 'conditional', 'freigegeben', false),
('patient', 'patient', 'vitals', 'conditional', 'freigegeben', false),
('patient', 'patient', 'internal_notes', 'hidden', NULL, true),
('patient', 'patient', 'travel_data', 'conditional', 'freigegeben', false);
