-- Fills the ISO citizenships (20261003100100_citizenships.sql) from the single
-- values stored before: the lead wizard's `registration_country` and
-- `patients.nationality`. A value counts when it is an ISO 3166-1 alpha-2 code
-- or a recognisable country name or demonym: the German, English and Russian
-- region names of every code (the source the frontend's
-- `countryCodeFromStoredValue` uses), legacy English names and the demonyms
-- the old patient form stored ("German", "Ukrainian", ...). Rows that already
-- have citizenships are left alone; values that match nothing stay where they
-- are and are counted in a NOTICE (the query in
-- docs/architecture/lead-payer-declaration_ua.md lists them).
--
-- Names are compared with lower() on both sides, so the match is
-- case-insensitive for every letter under a UTF-8 ctype and still exact for
-- non-ASCII letters under the C locale.
CREATE TEMP TABLE citizenship_backfill_names (
    name TEXT NOT NULL,
    code TEXT NOT NULL
);

INSERT INTO citizenship_backfill_names (name, code) VALUES
    ('Afghanistan', 'AF'),
    ('Ägypten', 'EG'),
    ('Åland Islands', 'AX'),
    ('Ålandinseln', 'AX'),
    ('Albania', 'AL'),
    ('Albanien', 'AL'),
    ('Algeria', 'DZ'),
    ('Algerien', 'DZ'),
    ('American', 'US'),
    ('American Samoa', 'AS'),
    ('Amerikanisch-Samoa', 'AS'),
    ('Amerikanische Jungferninseln', 'VI'),
    ('Amerikanische Überseeinseln', 'UM'),
    ('Andorra', 'AD'),
    ('Angola', 'AO'),
    ('Anguilla', 'AI'),
    ('Antarctica', 'AQ'),
    ('Antarktis', 'AQ'),
    ('Antigua & Barbuda', 'AG'),
    ('Antigua und Barbuda', 'AG'),
    ('Äquatorialguinea', 'GQ'),
    ('Argentina', 'AR'),
    ('Argentinien', 'AR'),
    ('Armenia', 'AM'),
    ('Armenian', 'AM'),
    ('Armenien', 'AM'),
    ('Aruba', 'AW'),
    ('Aserbaidschan', 'AZ'),
    ('Äthiopien', 'ET'),
    ('Australia', 'AU'),
    ('Australien', 'AU'),
    ('Austria', 'AT'),
    ('Austrian', 'AT'),
    ('Azerbaijan', 'AZ'),
    ('Azerbaijani', 'AZ'),
    ('Bahamas', 'BS'),
    ('Bahrain', 'BH'),
    ('Bangladesch', 'BD'),
    ('Bangladesh', 'BD'),
    ('Barbados', 'BB'),
    ('Belarus', 'BY'),
    ('Belarusian', 'BY'),
    ('Belgien', 'BE'),
    ('Belgium', 'BE'),
    ('Belize', 'BZ'),
    ('Benin', 'BJ'),
    ('Bermuda', 'BM'),
    ('Bhutan', 'BT'),
    ('Bolivia', 'BO'),
    ('Bolivien', 'BO'),
    ('Bosnia & Herzegovina', 'BA'),
    ('Bosnien und Herzegowina', 'BA'),
    ('Botsuana', 'BW'),
    ('Botswana', 'BW'),
    ('Bouvet Island', 'BV'),
    ('Bouvetinsel', 'BV'),
    ('Brasilien', 'BR'),
    ('Brazil', 'BR'),
    ('Brazilian', 'BR'),
    ('Brd', 'DE'),
    ('Britische Jungferninseln', 'VG'),
    ('Britisches Territorium im Indischen Ozean', 'IO'),
    ('British', 'GB'),
    ('British Indian Ocean Territory', 'IO'),
    ('British Virgin Islands', 'VG'),
    ('Brunei', 'BN'),
    ('Brunei Darussalam', 'BN'),
    ('Bulgaria', 'BG'),
    ('Bulgarien', 'BG'),
    ('Bundesrepublik deutschland', 'DE'),
    ('Burkina Faso', 'BF'),
    ('Burma', 'MM'),
    ('Burundi', 'BI'),
    ('Cabo Verde', 'CV'),
    ('Cambodia', 'KH'),
    ('Cameroon', 'CM'),
    ('Canada', 'CA'),
    ('Cape Verde', 'CV'),
    ('Caribbean Netherlands', 'BQ'),
    ('Cayman Islands', 'KY'),
    ('Central African Republic', 'CF'),
    ('Chad', 'TD'),
    ('Chile', 'CL'),
    ('China', 'CN'),
    ('Chinese', 'CN'),
    ('Christmas Island', 'CX'),
    ('Cocos (Keeling) Islands', 'CC'),
    ('Colombia', 'CO'),
    ('Comoros', 'KM'),
    ('Congo - Brazzaville', 'CG'),
    ('Congo - Kinshasa', 'CD'),
    ('Cook Islands', 'CK'),
    ('Cookinseln', 'CK'),
    ('Costa Rica', 'CR'),
    ('Cote d''ivoire', 'CI'),
    ('Côte d’Ivoire', 'CI'),
    ('Croatia', 'HR'),
    ('Cuba', 'CU'),
    ('Curaçao', 'CW'),
    ('Cyprus', 'CY'),
    ('Czech', 'CZ'),
    ('Czech republic', 'CZ'),
    ('Czechia', 'CZ'),
    ('Dänemark', 'DK'),
    ('Danish', 'DK'),
    ('Denmark', 'DK'),
    ('Deutsch', 'DE'),
    ('Deutschland', 'DE'),
    ('Djibouti', 'DJ'),
    ('Dominica', 'DM'),
    ('Dominican Republic', 'DO'),
    ('Dominikanische Republik', 'DO'),
    ('Dschibuti', 'DJ'),
    ('Dutch', 'NL'),
    ('East timor', 'TL'),
    ('Ecuador', 'EC'),
    ('Egypt', 'EG'),
    ('Egyptian', 'EG'),
    ('El Salvador', 'SV'),
    ('Emirates', 'AE'),
    ('Emirati', 'AE'),
    ('England', 'GB'),
    ('Equatorial Guinea', 'GQ'),
    ('Eritrea', 'ER'),
    ('Estland', 'EE'),
    ('Estonia', 'EE'),
    ('Eswatini', 'SZ'),
    ('Ethiopia', 'ET'),
    ('Falkland Islands', 'FK'),
    ('Falklandinseln', 'FK'),
    ('Faroe Islands', 'FO'),
    ('Färöer', 'FO'),
    ('Fidschi', 'FJ'),
    ('Fiji', 'FJ'),
    ('Finland', 'FI'),
    ('Finnland', 'FI'),
    ('France', 'FR'),
    ('Frankreich', 'FR'),
    ('Französisch-Guayana', 'GF'),
    ('Französisch-Polynesien', 'PF'),
    ('Französische Süd- und Antarktisgebiete', 'TF'),
    ('French', 'FR'),
    ('French Guiana', 'GF'),
    ('French Polynesia', 'PF'),
    ('French Southern Territories', 'TF'),
    ('Gabon', 'GA'),
    ('Gabun', 'GA'),
    ('Gambia', 'GM'),
    ('Georgia', 'GE'),
    ('Georgian', 'GE'),
    ('Georgien', 'GE'),
    ('German', 'DE'),
    ('Germany', 'DE'),
    ('Ghana', 'GH'),
    ('Ghanaian', 'GH'),
    ('Gibraltar', 'GI'),
    ('Great britain', 'GB'),
    ('Greece', 'GR'),
    ('Greek', 'GR'),
    ('Greenland', 'GL'),
    ('Grenada', 'GD'),
    ('Griechenland', 'GR'),
    ('Grönland', 'GL'),
    ('Grossbritannien', 'GB'),
    ('Großbritannien', 'GB'),
    ('Guadeloupe', 'GP'),
    ('Guam', 'GU'),
    ('Guatemala', 'GT'),
    ('Guernsey', 'GG'),
    ('Guinea', 'GN'),
    ('Guinea-Bissau', 'GW'),
    ('Guyana', 'GY'),
    ('Haiti', 'HT'),
    ('Heard & McDonald Islands', 'HM'),
    ('Heard und McDonaldinseln', 'HM'),
    ('Holland', 'NL'),
    ('Honduras', 'HN'),
    ('Hong Kong SAR China', 'HK'),
    ('Hungary', 'HU'),
    ('Iceland', 'IS'),
    ('India', 'IN'),
    ('Indien', 'IN'),
    ('Indonesia', 'ID'),
    ('Indonesien', 'ID'),
    ('Irak', 'IQ'),
    ('Iran', 'IR'),
    ('Iraq', 'IQ'),
    ('Ireland', 'IE'),
    ('Irland', 'IE'),
    ('Island', 'IS'),
    ('Isle of Man', 'IM'),
    ('Israel', 'IL'),
    ('Israeli', 'IL'),
    ('Italian', 'IT'),
    ('Italien', 'IT'),
    ('Italy', 'IT'),
    ('Ivory coast', 'CI'),
    ('Jamaica', 'JM'),
    ('Jamaika', 'JM'),
    ('Japan', 'JP'),
    ('Jemen', 'YE'),
    ('Jersey', 'JE'),
    ('Jordan', 'JO'),
    ('Jordanien', 'JO'),
    ('Kaimaninseln', 'KY'),
    ('Kambodscha', 'KH'),
    ('Kamerun', 'CM'),
    ('Kanada', 'CA'),
    ('Karibische Niederlande', 'BQ'),
    ('Kasachstan', 'KZ'),
    ('Katar', 'QA'),
    ('Kazakh', 'KZ'),
    ('Kazakhstan', 'KZ'),
    ('Kenia', 'KE'),
    ('Kenya', 'KE'),
    ('Kirgisistan', 'KG'),
    ('Kiribati', 'KI'),
    ('Kokosinseln', 'CC'),
    ('Kolumbien', 'CO'),
    ('Komoren', 'KM'),
    ('Kongo-Brazzaville', 'CG'),
    ('Kongo-Kinshasa', 'CD'),
    ('Kroatien', 'HR'),
    ('Kuba', 'CU'),
    ('Kuwait', 'KW'),
    ('Kyrgyzstan', 'KG'),
    ('Laos', 'LA'),
    ('Latvia', 'LV'),
    ('Latvian', 'LV'),
    ('Lebanon', 'LB'),
    ('Lesotho', 'LS'),
    ('Lettland', 'LV'),
    ('Libanon', 'LB'),
    ('Liberia', 'LR'),
    ('Libya', 'LY'),
    ('Libyen', 'LY'),
    ('Liechtenstein', 'LI'),
    ('Litauen', 'LT'),
    ('Lithuania', 'LT'),
    ('Luxembourg', 'LU'),
    ('Luxemburg', 'LU'),
    ('Macao SAR China', 'MO'),
    ('Macedonia', 'MK'),
    ('Madagascar', 'MG'),
    ('Madagaskar', 'MG'),
    ('Malawi', 'MW'),
    ('Malaysia', 'MY'),
    ('Maldives', 'MV'),
    ('Malediven', 'MV'),
    ('Mali', 'ML'),
    ('Malta', 'MT'),
    ('Marokko', 'MA'),
    ('Marshall Islands', 'MH'),
    ('Marshallinseln', 'MH'),
    ('Martinique', 'MQ'),
    ('Mauretanien', 'MR'),
    ('Mauritania', 'MR'),
    ('Mauritius', 'MU'),
    ('Mayotte', 'YT'),
    ('Mexico', 'MX'),
    ('Mexiko', 'MX'),
    ('Micronesia', 'FM'),
    ('Mikronesien', 'FM'),
    ('Moldova', 'MD'),
    ('Moldovan', 'MD'),
    ('Monaco', 'MC'),
    ('Mongolei', 'MN'),
    ('Mongolia', 'MN'),
    ('Montenegro', 'ME'),
    ('Montserrat', 'MS'),
    ('Morocco', 'MA'),
    ('Mosambik', 'MZ'),
    ('Mozambique', 'MZ'),
    ('Myanmar', 'MM'),
    ('Myanmar (Burma)', 'MM'),
    ('Myanmar/birma', 'MM'),
    ('Namibia', 'NA'),
    ('Nauru', 'NR'),
    ('Nepal', 'NP'),
    ('Netherlands', 'NL'),
    ('Neukaledonien', 'NC'),
    ('Neuseeland', 'NZ'),
    ('New Caledonia', 'NC'),
    ('New Zealand', 'NZ'),
    ('Nicaragua', 'NI'),
    ('Niederlande', 'NL'),
    ('Niger', 'NE'),
    ('Nigeria', 'NG'),
    ('Nigerian', 'NG'),
    ('Niue', 'NU'),
    ('Nordkorea', 'KP'),
    ('Nördliche Marianen', 'MP'),
    ('Nordmazedonien', 'MK'),
    ('Norfolk Island', 'NF'),
    ('Norfolkinsel', 'NF'),
    ('North Korea', 'KP'),
    ('North Macedonia', 'MK'),
    ('Northern Mariana Islands', 'MP'),
    ('Norway', 'NO'),
    ('Norwegen', 'NO'),
    ('Oesterreich', 'AT'),
    ('Oman', 'OM'),
    ('Österreich', 'AT'),
    ('Österreichisch', 'AT'),
    ('Pakistan', 'PK'),
    ('Pakistani', 'PK'),
    ('Palästinensische Autonomiegebiete', 'PS'),
    ('Palau', 'PW'),
    ('Palestinian Territories', 'PS'),
    ('Panama', 'PA'),
    ('Papua New Guinea', 'PG'),
    ('Papua-Neuguinea', 'PG'),
    ('Paraguay', 'PY'),
    ('Peru', 'PE'),
    ('Philippinen', 'PH'),
    ('Philippines', 'PH'),
    ('Pitcairn Islands', 'PN'),
    ('Pitcairninseln', 'PN'),
    ('Poland', 'PL'),
    ('Polen', 'PL'),
    ('Polish', 'PL'),
    ('Polnisch', 'PL'),
    ('Portugal', 'PT'),
    ('Puerto Rico', 'PR'),
    ('Qatar', 'QA'),
    ('Republik Moldau', 'MD'),
    ('Réunion', 'RE'),
    ('Romania', 'RO'),
    ('Ruanda', 'RW'),
    ('Rumänien', 'RO'),
    ('Russia', 'RU'),
    ('Russian', 'RU'),
    ('Russian federation', 'RU'),
    ('Russisch', 'RU'),
    ('Russische föderation', 'RU'),
    ('Russland', 'RU'),
    ('Rwanda', 'RW'),
    ('Salomonen', 'SB'),
    ('Sambia', 'ZM'),
    ('Samoa', 'WS'),
    ('San Marino', 'SM'),
    ('São Tomé & Príncipe', 'ST'),
    ('São Tomé und Príncipe', 'ST'),
    ('Saudi', 'SA'),
    ('Saudi Arabia', 'SA'),
    ('Saudi-Arabien', 'SA'),
    ('Schweden', 'SE'),
    ('Schweiz', 'CH'),
    ('Schweizerisch', 'CH'),
    ('Senegal', 'SN'),
    ('Serbia', 'RS'),
    ('Serbien', 'RS'),
    ('Seychellen', 'SC'),
    ('Seychelles', 'SC'),
    ('Sierra Leone', 'SL'),
    ('Simbabwe', 'ZW'),
    ('Singapore', 'SG'),
    ('Singapur', 'SG'),
    ('Sint Maarten', 'SX'),
    ('Slovakia', 'SK'),
    ('Slovenia', 'SI'),
    ('Slowakei', 'SK'),
    ('Slowenien', 'SI'),
    ('Solomon Islands', 'SB'),
    ('Somalia', 'SO'),
    ('Sonderverwaltungsregion Hongkong', 'HK'),
    ('Sonderverwaltungsregion Macau', 'MO'),
    ('South Africa', 'ZA'),
    ('South Georgia & South Sandwich Islands', 'GS'),
    ('South Korea', 'KR'),
    ('South Sudan', 'SS'),
    ('Spain', 'ES'),
    ('Spanien', 'ES'),
    ('Spanish', 'ES'),
    ('Spitzbergen und Jan Mayen', 'SJ'),
    ('Sri Lanka', 'LK'),
    ('St. Barthélemy', 'BL'),
    ('St. Helena', 'SH'),
    ('St. Kitts & Nevis', 'KN'),
    ('St. Kitts und Nevis', 'KN'),
    ('St. Lucia', 'LC'),
    ('St. Martin', 'MF'),
    ('St. Pierre & Miquelon', 'PM'),
    ('St. Pierre und Miquelon', 'PM'),
    ('St. Vincent & Grenadines', 'VC'),
    ('St. Vincent und die Grenadinen', 'VC'),
    ('Südafrika', 'ZA'),
    ('Sudan', 'SD'),
    ('Südgeorgien und die Südlichen Sandwichinseln', 'GS'),
    ('Südkorea', 'KR'),
    ('Südsudan', 'SS'),
    ('Suriname', 'SR'),
    ('Svalbard & Jan Mayen', 'SJ'),
    ('Swaziland', 'SZ'),
    ('Sweden', 'SE'),
    ('Swiss', 'CH'),
    ('Switzerland', 'CH'),
    ('Syria', 'SY'),
    ('Syrien', 'SY'),
    ('Tadschikistan', 'TJ'),
    ('Taiwan', 'TW'),
    ('Tajikistan', 'TJ'),
    ('Tansania', 'TZ'),
    ('Tanzania', 'TZ'),
    ('Thailand', 'TH'),
    ('The netherlands', 'NL'),
    ('Timor-Leste', 'TL'),
    ('Togo', 'TG'),
    ('Tokelau', 'TK'),
    ('Tonga', 'TO'),
    ('Trinidad & Tobago', 'TT'),
    ('Trinidad und Tobago', 'TT'),
    ('Tschad', 'TD'),
    ('Tschechien', 'CZ'),
    ('Tuerkei', 'TR'),
    ('Tunesien', 'TN'),
    ('Tunisia', 'TN'),
    ('Türkei', 'TR'),
    ('Turkey', 'TR'),
    ('Türkisch', 'TR'),
    ('Turkish', 'TR'),
    ('Türkiye', 'TR'),
    ('Turkmenistan', 'TM'),
    ('Turks & Caicos Islands', 'TC'),
    ('Turks- und Caicosinseln', 'TC'),
    ('Tuvalu', 'TV'),
    ('U.S. Outlying Islands', 'UM'),
    ('U.S. Virgin Islands', 'VI'),
    ('U.s.a.', 'US'),
    ('Uae', 'AE'),
    ('Uganda', 'UG'),
    ('Uk', 'GB'),
    ('Ukraina', 'UA'),
    ('Ukraine', 'UA'),
    ('Ukrainian', 'UA'),
    ('Ukrainisch', 'UA'),
    ('Ungarn', 'HU'),
    ('United Arab Emirates', 'AE'),
    ('United Kingdom', 'GB'),
    ('United States', 'US'),
    ('United states of america', 'US'),
    ('Uruguay', 'UY'),
    ('Usa', 'US'),
    ('Usbekistan', 'UZ'),
    ('Uzbek', 'UZ'),
    ('Uzbekistan', 'UZ'),
    ('Vanuatu', 'VU'),
    ('Vatican City', 'VA'),
    ('Vatikanstadt', 'VA'),
    ('Venezuela', 'VE'),
    ('Vereinigte Arabische Emirate', 'AE'),
    ('Vereinigte Staaten', 'US'),
    ('Vereinigtes Königreich', 'GB'),
    ('Vietnam', 'VN'),
    ('Wallis & Futuna', 'WF'),
    ('Wallis und Futuna', 'WF'),
    ('Weihnachtsinsel', 'CX'),
    ('Western Sahara', 'EH'),
    ('Westsahara', 'EH'),
    ('Yemen', 'YE'),
    ('Zambia', 'ZM'),
    ('Zentralafrikanische Republik', 'CF'),
    ('Zimbabwe', 'ZW'),
    ('Zypern', 'CY'),
    ('Австралия', 'AU'),
    ('Австрия', 'AT'),
    ('Азербайджан', 'AZ'),
    ('Аландские о-ва', 'AX'),
    ('Албания', 'AL'),
    ('Алжир', 'DZ'),
    ('Американское Самоа', 'AS'),
    ('Ангилья', 'AI'),
    ('Ангола', 'AO'),
    ('Андорра', 'AD'),
    ('Антарктида', 'AQ'),
    ('Антигуа и Барбуда', 'AG'),
    ('Аргентина', 'AR'),
    ('Армения', 'AM'),
    ('Аруба', 'AW'),
    ('Афганистан', 'AF'),
    ('Багамы', 'BS'),
    ('Бангладеш', 'BD'),
    ('Барбадос', 'BB'),
    ('Бахрейн', 'BH'),
    ('Беларусь', 'BY'),
    ('Белиз', 'BZ'),
    ('Белоруссия', 'BY'),
    ('Бельгия', 'BE'),
    ('Бенин', 'BJ'),
    ('Бермудские о-ва', 'BM'),
    ('Болгария', 'BG'),
    ('Боливия', 'BO'),
    ('Бонэйр, Синт-Эстатиус и Саба', 'BQ'),
    ('Босния и Герцеговина', 'BA'),
    ('Ботсвана', 'BW'),
    ('Бразилия', 'BR'),
    ('Британская территория в Индийском океане', 'IO'),
    ('Бруней', 'BN'),
    ('Буркина-Фасо', 'BF'),
    ('Бурунди', 'BI'),
    ('Бутан', 'BT'),
    ('Вануату', 'VU'),
    ('Ватикан', 'VA'),
    ('Великобритания', 'GB'),
    ('Венгрия', 'HU'),
    ('Венесуэла', 'VE'),
    ('Виргинские о-ва (Великобритания)', 'VG'),
    ('Виргинские о-ва (США)', 'VI'),
    ('Внешние малые о-ва (США)', 'UM'),
    ('Восточный Тимор', 'TL'),
    ('Вьетнам', 'VN'),
    ('Габон', 'GA'),
    ('Гаити', 'HT'),
    ('Гайана', 'GY'),
    ('Гамбия', 'GM'),
    ('Гана', 'GH'),
    ('Гваделупа', 'GP'),
    ('Гватемала', 'GT'),
    ('Гвинея', 'GN'),
    ('Гвинея-Бисау', 'GW'),
    ('Германия', 'DE'),
    ('Гернси', 'GG'),
    ('Гибралтар', 'GI'),
    ('Гондурас', 'HN'),
    ('Гонконг (САР)', 'HK'),
    ('Гренада', 'GD'),
    ('Гренландия', 'GL'),
    ('Греция', 'GR'),
    ('Грузия', 'GE'),
    ('Гуам', 'GU'),
    ('Дания', 'DK'),
    ('Джерси', 'JE'),
    ('Джибути', 'DJ'),
    ('Доминика', 'DM'),
    ('Доминиканская Республика', 'DO'),
    ('Египет', 'EG'),
    ('Замбия', 'ZM'),
    ('Западная Сахара', 'EH'),
    ('Зимбабве', 'ZW'),
    ('Израиль', 'IL'),
    ('Индия', 'IN'),
    ('Индонезия', 'ID'),
    ('Иордания', 'JO'),
    ('Ирак', 'IQ'),
    ('Иран', 'IR'),
    ('Ирландия', 'IE'),
    ('Исландия', 'IS'),
    ('Испания', 'ES'),
    ('Италия', 'IT'),
    ('Йемен', 'YE'),
    ('Кабо-Верде', 'CV'),
    ('Казахстан', 'KZ'),
    ('Камбоджа', 'KH'),
    ('Камерун', 'CM'),
    ('Канада', 'CA'),
    ('Катар', 'QA'),
    ('Кения', 'KE'),
    ('Кипр', 'CY'),
    ('Киргизия', 'KG'),
    ('Кирибати', 'KI'),
    ('Китай', 'CN'),
    ('КНДР', 'KP'),
    ('Кокосовые о-ва', 'CC'),
    ('Колумбия', 'CO'),
    ('Коморы', 'KM'),
    ('Конго - Браззавиль', 'CG'),
    ('Конго - Киншаса', 'CD'),
    ('Коста-Рика', 'CR'),
    ('Кот-д’Ивуар', 'CI'),
    ('Куба', 'CU'),
    ('Кувейт', 'KW'),
    ('Кыргызстан', 'KG'),
    ('Кюрасао', 'CW'),
    ('Лаос', 'LA'),
    ('Латвия', 'LV'),
    ('Лесото', 'LS'),
    ('Либерия', 'LR'),
    ('Ливан', 'LB'),
    ('Ливия', 'LY'),
    ('Литва', 'LT'),
    ('Лихтенштейн', 'LI'),
    ('Люксембург', 'LU'),
    ('Маврикий', 'MU'),
    ('Мавритания', 'MR'),
    ('Мадагаскар', 'MG'),
    ('Майотта', 'YT'),
    ('Макао (САР)', 'MO'),
    ('Малави', 'MW'),
    ('Малайзия', 'MY'),
    ('Мали', 'ML'),
    ('Мальдивы', 'MV'),
    ('Мальта', 'MT'),
    ('Марокко', 'MA'),
    ('Мартиника', 'MQ'),
    ('Маршалловы о-ва', 'MH'),
    ('Мексика', 'MX'),
    ('Мозамбик', 'MZ'),
    ('Молдавия', 'MD'),
    ('Молдова', 'MD'),
    ('Монако', 'MC'),
    ('Монголия', 'MN'),
    ('Монтсеррат', 'MS'),
    ('Мьянма (Бирма)', 'MM'),
    ('Намибия', 'NA'),
    ('Науру', 'NR'),
    ('Немец', 'DE'),
    ('Немка', 'DE'),
    ('Непал', 'NP'),
    ('Нигер', 'NE'),
    ('Нигерия', 'NG'),
    ('Нидерланды', 'NL'),
    ('Никарагуа', 'NI'),
    ('Ниуэ', 'NU'),
    ('Новая Зеландия', 'NZ'),
    ('Новая Каледония', 'NC'),
    ('Норвегия', 'NO'),
    ('О-в Буве', 'BV'),
    ('О-в Мэн', 'IM'),
    ('О-в Норфолк', 'NF'),
    ('О-в Рождества', 'CX'),
    ('О-в Св. Елены', 'SH'),
    ('О-ва Кайман', 'KY'),
    ('О-ва Кука', 'CK'),
    ('О-ва Питкэрн', 'PN'),
    ('О-ва Херд и Макдональд', 'HM'),
    ('ОАЭ', 'AE'),
    ('Оман', 'OM'),
    ('Пакистан', 'PK'),
    ('Палау', 'PW'),
    ('Палестинские территории', 'PS'),
    ('Панама', 'PA'),
    ('Папуа — Новая Гвинея', 'PG'),
    ('Парагвай', 'PY'),
    ('Перу', 'PE'),
    ('Польша', 'PL'),
    ('Португалия', 'PT'),
    ('Пуэрто-Рико', 'PR'),
    ('Республика Корея', 'KR'),
    ('Реюньон', 'RE'),
    ('Российская федерация', 'RU'),
    ('Россия', 'RU'),
    ('Руанда', 'RW'),
    ('Румыния', 'RO'),
    ('Русская', 'RU'),
    ('Русский', 'RU'),
    ('Рф', 'RU'),
    ('Сальвадор', 'SV'),
    ('Самоа', 'WS'),
    ('Сан-Марино', 'SM'),
    ('Сан-Томе и Принсипи', 'ST'),
    ('Саудовская Аравия', 'SA'),
    ('Северная Македония', 'MK'),
    ('Северные Марианские о-ва', 'MP'),
    ('Сейшельские о-ва', 'SC'),
    ('Сен-Бартелеми', 'BL'),
    ('Сен-Мартен', 'MF'),
    ('Сен-Пьер и Микелон', 'PM'),
    ('Сенегал', 'SN'),
    ('Сент-Винсент и Гренадины', 'VC'),
    ('Сент-Китс и Невис', 'KN'),
    ('Сент-Люсия', 'LC'),
    ('Сербия', 'RS'),
    ('Сингапур', 'SG'),
    ('Синт-Мартен', 'SX'),
    ('Сирия', 'SY'),
    ('Словакия', 'SK'),
    ('Словения', 'SI'),
    ('Соединенные Штаты', 'US'),
    ('Соломоновы о-ва', 'SB'),
    ('Сомали', 'SO'),
    ('Судан', 'SD'),
    ('Суринам', 'SR'),
    ('Сша', 'US'),
    ('Сьерра-Леоне', 'SL'),
    ('Таджикистан', 'TJ'),
    ('Таиланд', 'TH'),
    ('Тайвань', 'TW'),
    ('Танзания', 'TZ'),
    ('Тёркс и Кайкос', 'TC'),
    ('Того', 'TG'),
    ('Токелау', 'TK'),
    ('Тонга', 'TO'),
    ('Тринидад и Тобаго', 'TT'),
    ('Тувалу', 'TV'),
    ('Тунис', 'TN'),
    ('Туркменистан', 'TM'),
    ('Турция', 'TR'),
    ('Уганда', 'UG'),
    ('Узбекистан', 'UZ'),
    ('Украина', 'UA'),
    ('Украинец', 'UA'),
    ('Украинка', 'UA'),
    ('Уоллис и Футуна', 'WF'),
    ('Уругвай', 'UY'),
    ('Фарерские о-ва', 'FO'),
    ('Федеративные Штаты Микронезии', 'FM'),
    ('Фиджи', 'FJ'),
    ('Филиппины', 'PH'),
    ('Финляндия', 'FI'),
    ('Фолклендские о-ва', 'FK'),
    ('Франция', 'FR'),
    ('Французская Гвиана', 'GF'),
    ('Французская Полинезия', 'PF'),
    ('Французские Южные территории', 'TF'),
    ('Хорватия', 'HR'),
    ('Центрально-Африканская Республика', 'CF'),
    ('Чад', 'TD'),
    ('Черногория', 'ME'),
    ('Чехия', 'CZ'),
    ('Чили', 'CL'),
    ('Швейцария', 'CH'),
    ('Швеция', 'SE'),
    ('Шпицберген и Ян-Майен', 'SJ'),
    ('Шри-Ланка', 'LK'),
    ('Эквадор', 'EC'),
    ('Экваториальная Гвинея', 'GQ'),
    ('Эритрея', 'ER'),
    ('Эсватини', 'SZ'),
    ('Эстония', 'EE'),
    ('Эфиопия', 'ET'),
    ('Южная Георгия и Южные Сандвичевы о-ва', 'GS'),
    ('Южно-Африканская Республика', 'ZA'),
    ('Южный Судан', 'SS'),
    ('Ямайка', 'JM'),
    ('Япония', 'JP');

CREATE TEMP TABLE citizenship_backfill_codes AS
SELECT DISTINCT code FROM citizenship_backfill_names;

UPDATE leads
SET citizenships = ARRAY[resolved.code]
FROM (
    SELECT lead.id,
           COALESCE(
               (SELECT codes.code FROM citizenship_backfill_codes codes
                 WHERE codes.code = upper(btrim(lead.wizard_state ->> 'registration_country'))),
               (SELECT names.code FROM citizenship_backfill_names names
                 WHERE lower(names.name) = lower(btrim(lead.wizard_state ->> 'registration_country'))
                 LIMIT 1)
           ) AS code
    FROM leads lead
    WHERE lead.citizenships = '{}'::text[]
      AND NULLIF(btrim(lead.wizard_state ->> 'registration_country'), '') IS NOT NULL
) resolved
WHERE leads.id = resolved.id
  AND resolved.code IS NOT NULL;

UPDATE patients
SET citizenships = ARRAY[resolved.code]
FROM (
    SELECT patient.id,
           COALESCE(
               (SELECT codes.code FROM citizenship_backfill_codes codes
                 WHERE codes.code = upper(btrim(patient.nationality))),
               (SELECT names.code FROM citizenship_backfill_names names
                 WHERE lower(names.name) = lower(btrim(patient.nationality))
                 LIMIT 1)
           ) AS code
    FROM patients patient
    WHERE patient.citizenships = '{}'::text[]
      AND NULLIF(btrim(patient.nationality), '') IS NOT NULL
) resolved
WHERE patients.id = resolved.id
  AND resolved.code IS NOT NULL;

DO $$
DECLARE
    unmapped_leads BIGINT;
    unmapped_patients BIGINT;
BEGIN
    SELECT count(*) INTO unmapped_leads
    FROM leads
    WHERE citizenships = '{}'::text[]
      AND NULLIF(btrim(wizard_state ->> 'registration_country'), '') IS NOT NULL;
    SELECT count(*) INTO unmapped_patients
    FROM patients
    WHERE citizenships = '{}'::text[]
      AND NULLIF(btrim(nationality), '') IS NOT NULL;
    RAISE NOTICE 'citizenship backfill: % lead and % patient values stay unmapped',
        unmapped_leads, unmapped_patients;
END $$;

DROP TABLE citizenship_backfill_codes;
DROP TABLE citizenship_backfill_names;
