-- External clinic/provider invoices are not all agency cash expenses. Record who
-- actually paid and expose the resulting patient receivable/provider liability.

ALTER TABLE external_invoices
    ADD COLUMN IF NOT EXISTS paid_by TEXT NOT NULL DEFAULT 'unpaid',
    ADD COLUMN IF NOT EXISTS service_delivered BOOLEAN NOT NULL DEFAULT false;

UPDATE external_invoices
SET paid_by = CASE WHEN status = 'paid' THEN 'agency' ELSE 'unpaid' END,
    service_delivered = CASE WHEN status = 'paid' THEN true ELSE service_delivered END
WHERE paid_by = 'unpaid';

ALTER TABLE external_invoices
    DROP CONSTRAINT IF EXISTS external_invoices_paid_by_check;

ALTER TABLE external_invoices
    ADD CONSTRAINT external_invoices_paid_by_check
    CHECK (paid_by IN ('patient', 'agency', 'unpaid'));

ALTER TABLE external_invoices
    DROP CONSTRAINT IF EXISTS external_invoices_payment_state_consistent;

ALTER TABLE external_invoices
    ADD CONSTRAINT external_invoices_payment_state_consistent
    CHECK ((status = 'paid') = (paid_by <> 'unpaid'));

ALTER TABLE external_invoices
    ADD COLUMN IF NOT EXISTS patient_receivable_gross NUMERIC(12, 2)
        GENERATED ALWAYS AS (
            CASE
                WHEN status <> 'cancelled'
                 AND (
                    paid_by = 'agency'
                    OR (paid_by = 'unpaid' AND service_delivered)
                 )
                    THEN amount_gross
                ELSE 0
            END
        ) STORED,
    ADD COLUMN IF NOT EXISTS provider_liability_gross NUMERIC(12, 2)
        GENERATED ALWAYS AS (
            CASE
                WHEN status <> 'cancelled' AND paid_by = 'unpaid'
                    THEN amount_gross
                ELSE 0
            END
        ) STORED;

CREATE INDEX IF NOT EXISTS idx_external_invoices_patient_receivable
    ON external_invoices(patient_id, patient_receivable_gross)
    WHERE patient_receivable_gross > 0;

CREATE INDEX IF NOT EXISTS idx_external_invoices_provider_liability
    ON external_invoices(provider_id, provider_liability_gross)
    WHERE provider_liability_gross > 0;

COMMENT ON COLUMN external_invoices.paid_by IS
    'Who settled the provider invoice: patient, agency (GMED), or unpaid.';
COMMENT ON COLUMN external_invoices.patient_receivable_gross IS
    'Patient outstanding generated by an agency-paid cost or a delivered but unpaid service.';
COMMENT ON COLUMN external_invoices.provider_liability_gross IS
    'Expected provider cost still unpaid by both patient and GMED.';
