import { expect, test, type Page } from "@playwright/test";

// The expanded row of the leads list: the state of the lead's patient portal
// at a glance (owner feedback 2026-10-05). Mocked API, synthetic data.

const baseLead = {
  phone: "+49 30 100001",
  source: "manual",
  country: "DE",
  citizenships: ["DE"],
  intake_source: "manual",
  flow: "medical",
  lead_type: "console",
  console_promoted_at: "2026-10-05T12:00:00Z",
  qualification_status: "in_progress",
  compliance_status: "pending",
  conversion_ready: false,
  failed_outcome: { status: "none", reason: null, note: null, processed_at: null },
  attachment_count: 0,
  retention_deadline_at: "2026-10-19T12:00:00Z",
};

const leads = [
  {
    ...baseLead,
    id: "00000000-0000-0000-0000-000000000a01",
    first_name: "Anton",
    last_name: "Testovich",
    email: "anton.testovich@example.com",
    submitted_at: "2026-10-05T12:00:00Z",
    created_at: "2026-10-05T12:00:00Z",
    portal_account: { user_id: "u-anton", is_active: true, password_change_pending: false, last_login_at: null },
    portal_intake: { filled: 2, total: 12, documents: 0, guardians: 0, submitted_at: null },
  },
  {
    ...baseLead,
    id: "00000000-0000-0000-0000-000000000a02",
    first_name: "Sofia",
    last_name: "Beispiel",
    email: "sofia.beispiel@example.com",
    submitted_at: "2026-10-05T11:00:00Z",
    created_at: "2026-10-05T11:00:00Z",
    portal_account: { user_id: "u-sofia", is_active: true, password_change_pending: false, last_login_at: "2026-10-05T12:10:00Z" },
    portal_intake: { filled: 12, total: 12, documents: 3, guardians: 0, submitted_at: "2026-10-05T12:30:00Z" },
  },
];

type MailMock = {
  /** Mittaro is connected. */
  available?: boolean;
  /** The provider refuses the e-mail. */
  failSend?: boolean;
};
type Call = { method: string; path: string; body: unknown };

/** The portal state of a lead who is a child: one parent on file, no login for her yet. */
function minorPortalIntake(leadId: string) {
  return {
    lead_id: leadId,
    fill_mode: "patient",
    patient_fields: {},
    patient_payer: null,
    progress: { filled: 2, total: 12, documents: 0, submitted_at: null },
    submitted_at: null,
    submitted_by: null,
    consents: [],
    uploads: [],
    uploads_hidden: false,
    guardians: {
      links: [],
      candidates: [
        {
          trusted_contact_id: "11111111-1111-4111-8111-111111111111",
          name: "Anna Muster",
          relation: "parent",
          email: "anna.muster@example.com",
          access_id: null,
        },
      ],
    },
    minor: true,
    can_issue: true,
    can_review_uploads: true,
  };
}

async function setup(page: Page, lang: "ru" | "de", mail: MailMock = {}, minorLeadId?: string) {
  const calls: Call[] = [];
  await page.addInitScript((language) => {
    localStorage.setItem("gmed_lang", language);
    localStorage.setItem("gmed_access_token", "lead-portal-row-token");
    localStorage.setItem("gmed_refresh_token", "lead-portal-row-refresh");
  }, lang);
  await page.routeWebSocket("**/api/**", (socket) => socket.close());
  await page.route("**/api/v1/**", async (route) => {
    const path = new URL(route.request().url()).pathname.replace("/api/v1", "");
    if (path === "/me") {
      return route.fulfill({
        json: { id: "ceo-1", email: "ceo@example.com", name: "CEO Test", role: "ceo", created_at: "2026-01-01T00:00:00Z" },
      });
    }
    if (path === "/leads") return route.fulfill({ json: leads });
    const method = route.request().method();
    // The GwG identification sheet: generated by the server, then downloaded.
    if (path === "/documents/generate" && method === "POST") {
      calls.push({ method, path, body: route.request().postDataJSON() });
      return route.fulfill({
        json: {
          id: "doc-gwg-1",
          document_number: "GWG-20261005-0001",
          auto_name: "Dokumentationsbogen natürliche Personen",
          original_filename: "Dokumentationsbogen natuerliche Personen.pdf",
          mime_type: "application/pdf",
          file_size: 20,
        },
      });
    }
    if (path === "/documents/doc-gwg-1/download") {
      return route.fulfill({ contentType: "application/pdf", body: Buffer.from("%PDF-1.4\n%%EOF\n") });
    }
    const lead = leads.find((item) => path.startsWith(`/leads/${item.id}/`));
    if (lead && method === "POST") {
      calls.push({ method, path: path.replace(`/leads/${lead.id}`, ""), body: route.request().postDataJSON() });
    }
    if (lead && lead.id === minorLeadId && path.endsWith("/portal-intake")) {
      return route.fulfill({ json: minorPortalIntake(lead.id) });
    }
    if (lead && path.endsWith("/portal-login-email")) {
      if (method === "POST") {
        if (mail.failSend) {
          return route.fulfill({ status: 503, json: { code: "mail_unavailable", error: "Mail service unavailable" } });
        }
        return route.fulfill({
          json: {
            sent_to: lead.email,
            // 15:42 in Berlin.
            sent_at: "2026-10-05T13:42:00Z",
            language: (route.request().postDataJSON() as { language: string }).language,
            message_id: "email_01TEST",
            replayed: false,
          },
        });
      }
      return route.fulfill({
        json: {
          available: mail.available ?? true,
          reason_code: mail.available === false ? "mail_not_configured" : "ready",
          can_send: true,
          lead_language: "uk",
          sent: [],
        },
      });
    }
    if (lead && path.endsWith("/portal-account") && method === "POST") {
      return route.fulfill({
        json: { user_id: lead.portal_account.user_id, email: lead.email, created: false, one_time_password: "Kq7-mP2x-Rw9t" },
      });
    }
    return route.fulfill({ json: [] });
  });
  return calls;
}

test("the expanded lead row shows the patient portal at a glance", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await setup(page, "ru");
  await page.goto("/leads");

  // The frozen name column renders the cell twice; either button opens the row.
  await page.getByTestId(`lead-expand-${leads[0].id}`).first().click();
  await page.getByTestId(`lead-expand-${leads[1].id}`).first().click();
  // The table renders a row once per pane (frozen and scrolling): take the first.
  const rows = page.getByTestId("lead-portal-access");

  // Not signed in yet: every fact has its own caption.
  const fresh = rows.filter({ hasText: "anton.testovich@example.com" }).first();
  await expect(fresh).toContainText("Портал пациента");
  await expect(fresh).toContainText("Ещё не входил");
  await expect(fresh).toContainText("Последний вход");
  await expect(fresh).toContainText("ещё не было");
  await expect(fresh).toContainText("Доступ до");
  await expect(fresh).toContainText("19.10.2026");
  await expect(fresh.getByTestId("lead-portal-progress")).toContainText("2 из 12 полей");
  await expect(fresh).toContainText("Отправлено");
  await expect(fresh).toContainText("ещё нет");

  // Filled in and sent.
  const sent = rows.filter({ hasText: "sofia.beispiel@example.com" }).first();
  await expect(sent).toContainText("Входил");
  await expect(sent.getByTestId("lead-portal-progress")).toContainText("12 из 12 полей");
  await expect(sent).toContainText("05.10.2026 14:30");

  // "New password" is the one action of the row: the brand button, not an outline one.
  const action = fresh.getByRole("button", { name: "Новый пароль" });
  await expect(action).toBeVisible();
  const colours = await action.evaluate((button) => {
    const probe = document.createElement("span");
    probe.style.color = "var(--brand)";
    document.body.append(probe);
    const brand = getComputedStyle(probe).color;
    probe.remove();
    return { background: getComputedStyle(button).backgroundColor, brand };
  });
  expect(colours.background).toBe(colours.brand);
  // It stands right beside the status, not at the far end of the wide row.
  const badge = await fresh.getByText("Ещё не входил", { exact: true }).boundingBox();
  const button = await action.boundingBox();
  expect(button!.x - (badge!.x + badge!.width)).toBeLessThan(40);

  await page.screenshot({ path: "test-results/lead-portal-row.png" });
});

test("the patient portal row reads in German too", async ({ page }) => {
  await setup(page, "de");
  await page.goto("/leads");
  await page.getByTestId(`lead-expand-${leads[1].id}`).first().click();
  const row = page.getByTestId("lead-portal-access").first();
  await expect(row).toContainText("Patientenportal");
  await expect(row).toContainText("Letzte Anmeldung");
  await expect(row.getByTestId("lead-portal-progress")).toContainText("12 von 12 Feldern");
  await expect(row).toContainText("Gesendet");
  await expect(row.getByRole("button", { name: "Neues Passwort" })).toBeVisible();
});

test("one click issues a new password and e-mails the access to the lead", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  const calls = await setup(page, "ru");
  await page.goto("/leads");
  await page.getByTestId(`lead-expand-${leads[1].id}`).first().click();
  const row = page.getByTestId("lead-portal-access").first();

  // The second action of the row, right after "New password".
  const send = row.getByTestId("lead-portal-send-email");
  await expect(send).toHaveText("Отправить доступ на e-mail");
  await expect(send).toBeEnabled();
  const reset = await row.getByRole("button", { name: "Новый пароль" }).boundingBox();
  const sendBox = await send.boundingBox();
  expect(sendBox!.x - (reset!.x + reset!.width)).toBeLessThan(40);

  await send.click();
  const dialog = page.getByTestId("lead-portal-email-dialog");
  // The stored hash cannot be sent: the dialog says a new password replaces the old one.
  await expect(dialog).toContainText("старый перестанет работать");
  await expect(dialog).toContainText("открытые сессии пациента будут завершены");
  await expect(dialog).toContainText("sofia.beispiel@example.com");
  // The lead's own language is preselected and can be changed.
  await expect(dialog.getByRole("button", { name: "UA", exact: true })).toHaveAttribute("aria-pressed", "true");
  await dialog.getByRole("button", { name: "EN", exact: true }).click();
  expect(calls).toEqual([]);

  await dialog.getByTestId("lead-portal-email-confirm").click();
  await expect(row.getByTestId("lead-portal-email-notice")).toHaveText(
    "Доступ отправлен на sofia.beispiel@example.com · 05.10.2026 15:42",
  );
  await expect(dialog).toBeHidden();
  // The password went into the e-mail, not onto the screen.
  await expect(page.getByTestId("portal-credentials-password")).toHaveCount(0);
  expect(calls).toEqual([
    { method: "POST", path: "/portal-account", body: {} },
    { method: "POST", path: "/portal-login-email", body: { user_id: "u-sofia", password: "Kq7-mP2x-Rw9t", language: "en" } },
  ]);
});

test("without a mail connection the button explains instead of replacing the password", async ({ page }) => {
  const calls = await setup(page, "de", { available: false });
  await page.goto("/leads");
  await page.getByTestId(`lead-expand-${leads[1].id}`).first().click();
  const row = page.getByTestId("lead-portal-access").first();
  await row.getByRole("button", { name: "Zugang per E-Mail senden" }).click();
  const dialog = page.getByTestId("lead-portal-email-dialog");
  await expect(dialog).toContainText("Der E-Mail-Versand ist nicht eingerichtet");
  await expect(dialog).toContainText("API-Verbindungen");
  await expect(dialog.getByTestId("lead-portal-email-confirm")).toHaveCount(0);
  // The window has its own corner button of the same name; this is the footer one.
  await dialog.getByRole("button", { name: "Schließen", exact: true }).first().click();
  await expect(dialog).toBeHidden();
  expect(calls).toEqual([]);
});

test("a failed e-mail hands the new password over in the usual window", async ({ page }) => {
  const calls = await setup(page, "ru", { failSend: true });
  await page.goto("/leads");
  await page.getByTestId(`lead-expand-${leads[1].id}`).first().click();
  const row = page.getByTestId("lead-portal-access").first();
  await row.getByTestId("lead-portal-send-email").click();
  await page.getByTestId("lead-portal-email-confirm").click();

  // The old password is gone already, so the new one must not be lost.
  await expect(page.getByTestId("portal-credentials-password")).toHaveText("Kq7-mP2x-Rw9t");
  await expect(row).toContainText("Письмо не отправлено: Сервис e-mail временно недоступен");
  await expect(row).toContainText("Новый пароль уже действует");
  await expect(row.getByTestId("lead-portal-email-notice")).toHaveCount(0);
  expect(calls.map((call) => call.path)).toEqual(["/portal-account", "/portal-login-email"]);
});

test("the GwG identification sheet of the lead downloads from the row", async ({ page }) => {
  const calls = await setup(page, "ru");
  await page.goto("/leads");
  await page.getByTestId(`lead-expand-${leads[1].id}`).first().click();
  const row = page.getByTestId("lead-portal-access").first();
  const sheet = row.getByTestId("lead-gwg-sheet");
  await expect(sheet).toHaveText("Doku-Bogen GwG");

  await expect(row.getByTestId("lead-gwg-sheet-notice")).toHaveCount(0);
  const download = page.waitForEvent("download");
  await sheet.click();
  expect((await download).suggestedFilename()).toBe("Dokumentationsbogen natuerliche Personen.pdf");
  // The row says that the sheet was made, and when.
  await expect(row.getByTestId("lead-gwg-sheet-notice")).toHaveText(/^Сформирован \d{2}\.\d{2}\.\d{4} \d{2}:\d{2}$/);
  // Nothing is typed: the server fills the sheet of the patient from the lead.
  expect(calls).toEqual([
    {
      method: "POST",
      path: "/documents/generate",
      body: expect.objectContaining({
        template_id: "gwg_identification",
        lead_id: leads[1].id,
        bindings: { gwg_identification: { subject: "contract_partner" } },
      }),
    },
  ]);
});

test("a minor without a login is offered no access of his own: the parents get theirs", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await setup(page, "ru", {}, leads[0].id);
  // The child has no login yet (registered after setup, so it wins for the list).
  await page.route((url) => url.pathname === "/api/v1/leads", (route) =>
    route.fulfill({ json: leads.map((lead, index) => (index === 0 ? { ...lead, portal_account: null } : lead)) }));
  await page.goto("/leads");
  await page.getByTestId(`lead-expand-${leads[0].id}`).first().click();
  const minor = page.getByTestId("lead-portal-access").first();
  await expect(minor.getByTestId("lead-guardian-access")).toContainText("Anna Muster");
  await expect(minor).toContainText("У ребёнка нет своего доступа: доступ получают родители (ниже).");
  await expect(minor.getByRole("button", { name: "Создать доступ" })).toHaveCount(0);
  await expect(minor.getByTestId("lead-portal-send-email")).toHaveCount(0);
});

test("a minor lead has no quick sheet button: the sheets are made per parent in the wizard", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  const calls = await setup(page, "ru", {}, leads[0].id);
  await page.goto("/leads");
  await page.getByTestId(`lead-expand-${leads[0].id}`).first().click();
  await page.getByTestId(`lead-expand-${leads[1].id}`).first().click();
  const rows = page.getByTestId("lead-portal-access");

  // The child: the parents' block is loaded, and the row offers no sheet.
  const minor = rows.filter({ hasText: "anton.testovich@example.com" }).first();
  await expect(minor.getByTestId("lead-guardian-access")).toContainText("Доступ родителей (несовершеннолетний)");
  await expect(minor.getByTestId("lead-guardian-access")).toContainText("Anna Muster");
  await expect(minor.getByTestId("lead-gwg-sheet")).toHaveCount(0);
  // The other actions of the row stay.
  await expect(minor.getByRole("button", { name: "Новый пароль" })).toBeVisible();
  await expect(minor.getByTestId("lead-portal-send-email")).toBeVisible();

  // An adult keeps the button.
  const adult = rows.filter({ hasText: "sofia.beispiel@example.com" }).first();
  await expect(adult.getByTestId("lead-gwg-sheet")).toHaveText("Doku-Bogen GwG");
  expect(calls.filter((call) => call.path === "/documents/generate")).toEqual([]);
});
