export const liveRu = {
  connectionScope: "Подключение действует для разрешённых в DATEV данных. Доступ к конкретной компании проверяется отдельно по Beraternummer и Mandantennummer.",
  title: "Доступ к DATEV", hint: "Подключение и чтение данных выбранной компании. Запись в DATEV отключена.",
  unavailable: "Состояние неизвестно", companyMissing: "Сначала сохраните действительные Beraternummer и Mandantennummer в профиле компании.", historyError: "Не удалось загрузить журнал. Обновите статус, чтобы повторить.", exchangeMissing: "Чтение требует подписки и авторизации Export Rechnungswesen. Настройте ключи с этим доступом и подключитесь повторно.", unavailableOperations: "Импорт оригиналов из DATEV, отправка данных в DATEV и проведение платежей пока недоступны. Скачивание JSON не выполняет эти операции.",
  loading: "Загрузка подключения…", refresh: "DATEV · Обновить статус", settings: "Ключи приложения", mode: "Среда DATEV",
  id: "Client ID приложения", secret: "Client Secret", redirect: "Redirect URL", save: "DATEV · Сохранить ключи",
  keyHint: "Ключи сохраняются зашифрованными на сервере. Redirect URL должен точно совпадать с адресом в DATEV Developer Portal.",
  exchange: "Запрашивать доступ к Export Rechnungswesen (accounting:dataexchange)",
  exchangeHint: "Включайте, если API-продукт подключён для приложения. Галочка не подтверждает права или заказ сервиса.",
  connect: "Подключить через DATEV", disconnect: "DATEV · Отключить доступ", check: "DATEV · Проверить доступ",
  disconnected: "Не подключено", connected: "Авторизовано", notConfigured: "Ключи не настроены", reconnect: "Требуется повторный вход", revoking: "Отзыв доступа не подтверждён",
  saved: "Ключи сохранены. Теперь подключитесь через DATEV.", callbackOk: "Авторизация завершена. Проверьте доступ к выбранной компании.", callbackFailed: "Авторизация не завершена. Повторите вход и проверьте настройки приложения.",
  checked: "Последняя проверка компании", never: "Ещё не проверено", expires: "Токен действует до",
  numbersHint: "Сначала сохраните Beraternummer и Mandantennummer в профиле ниже. Проверка относится только к этой компании.",
  services: "Сервисы, возвращённые DATEV", servicesHint: "Наличие сервиса в ответе не подтверждает загрузку документов или поддержку всех функций модуля.",
  noServices: "DATEV не вернул список сервисов для этой компании.",
  readTitle: "Получение данных", readHint: "Данные Export Rechnungswesen относятся к последней архивации в DATEV. Получение не создаёт счета в GMed.",
  originals: "Загрузка оригиналов PDF/XML из Belege online пока не поддерживается этим коннектором. Файл, выгруженный вручную из DATEV, можно импортировать через входящие инвойсы.",
  fiscal: "Финансовые годы", terms: "Условия платежей", balances: "Обороты и остатки", kind: "Какие данные получить",
  year: "Начало финансового года", yearHint: "Выберите дату начала из результата «Финансовые годы»; она может отличаться от 1 января.",
  read: "Получить из DATEV", download: "DATEV · Скачать JSON", empty: "Запрос выполнен: данных нет.",
  count: "Получено записей", first: "Показаны первые 50 записей. Скачать можно весь полученный результат.",
  details: "Открыть поля записи", history: "Журнал обмена", noHistory: "Операций пока нет.", success: "Успешно", failed: "Не выполнено", started: "Начато",
  revokeLink: "Управление доступом на стороне DATEV", busy: "Выполняется…", genericError: "Не удалось выполнить запрос. Проверьте подключение и повторите.",
  connectLong: "DATEV · Подключить на длительный срок", forceDisconnect: "DATEV · Отключить без подтверждения",
  session: "Вход в DATEV действует до", sessionHint: "Обычный вход DATEV действует не более 11 часов, затем потребуется повторный вход. Длительный доступ (до 2 лет) выдаётся только для одной проверенной компании.",
  longTerm: "Длительный доступ", longTermFor: "Длительный доступ для компании", longTermNeedsCheck: "Длительное подключение доступно после успешной проверки доступа к компании из профиля: подключитесь обычным входом, выполните «Проверить доступ», затем отключитесь.",
  forcedNotice: "Токены удалены в GMed, но DATEV не подтвердил отзыв. Отзовите доступ приложения на стороне DATEV (ссылка ниже).",
};
export const liveDe: typeof liveRu = {
  connectionScope: "Die Verbindung gilt für die in DATEV freigegebenen Daten. Der Zugriff auf ein Unternehmen wird separat anhand von Beraternummer und Mandantennummer geprüft.",
  title: "DATEV-Zugriff", hint: "Verbindung und Datenabruf für das ausgewählte Unternehmen. Schreiben in DATEV ist deaktiviert.",
  unavailable: "Status unbekannt", companyMissing: "Zuerst gültige Beraternummer und Mandantennummer im Unternehmensprofil speichern.", historyError: "Protokoll konnte nicht geladen werden. Status aktualisieren und erneut versuchen.", exchangeMissing: "Der Abruf erfordert ein Abonnement und die Autorisierung für Export Rechnungswesen. Zugangsdaten mit diesem Zugriff einrichten und erneut verbinden.", unavailableOperations: "Originalbelege aus DATEV importieren, Daten an DATEV übertragen und Zahlungen ausführen ist derzeit nicht verfügbar. Der JSON-Download führt diese Aktionen nicht aus.",
  loading: "Verbindung wird geladen…", refresh: "DATEV · Status aktualisieren", settings: "App-Zugangsdaten", mode: "DATEV-Umgebung",
  id: "Client ID der App", secret: "Client Secret", redirect: "Redirect URL", save: "DATEV · Zugangsdaten speichern",
  keyHint: "Zugangsdaten werden serverseitig verschlüsselt gespeichert. Die Redirect URL muss exakt dem Eintrag im DATEV Developer Portal entsprechen.",
  exchange: "Zugriff auf Export Rechnungswesen anfordern (accounting:dataexchange)",
  exchangeHint: "Aktivieren, wenn die App dieses API-Produkt abonniert hat. Diese Auswahl bestätigt weder Berechtigungen noch eine Servicebestellung.",
  connect: "Mit DATEV verbinden", disconnect: "DATEV · Zugriff trennen", check: "DATEV · Zugriff prüfen",
  disconnected: "Nicht verbunden", connected: "Autorisiert", notConfigured: "Zugangsdaten fehlen", reconnect: "Erneute Anmeldung erforderlich", revoking: "Widerruf nicht bestätigt",
  saved: "Zugangsdaten gespeichert. Jetzt mit DATEV verbinden.", callbackOk: "Autorisierung abgeschlossen. Zugriff auf das ausgewählte Unternehmen prüfen.", callbackFailed: "Autorisierung nicht abgeschlossen. Anmeldung wiederholen und App-Einstellungen prüfen.",
  checked: "Letzte Prüfung des Unternehmens", never: "Noch nicht geprüft", expires: "Token gültig bis",
  numbersHint: "Zuerst Beraternummer und Mandantennummer im Profil unten speichern. Die Prüfung gilt nur für dieses Unternehmen.",
  services: "Von DATEV zurückgegebene Services", servicesHint: "Ein Service im Ergebnis bestätigt weder einen Belegdownload noch die Unterstützung aller Modulfunktionen.",
  noServices: "DATEV hat für dieses Unternehmen keine Services zurückgegeben.",
  readTitle: "Daten abrufen", readHint: "Export Rechnungswesen liefert den Stand der letzten DATEV-Archivierung. Der Abruf erstellt keine Rechnungen in GMed.",
  originals: "PDF/XML-Originale aus Belege online können mit diesem Connector noch nicht abgerufen werden. Manuell aus DATEV exportierte Dateien können über den Rechnungseingang importiert werden.",
  fiscal: "Wirtschaftsjahre", terms: "Zahlungsbedingungen", balances: "Summen und Salden", kind: "Daten auswählen",
  year: "Beginn des Wirtschaftsjahres", yearHint: "Das Anfangsdatum aus dem Ergebnis „Wirtschaftsjahre“ auswählen; es kann vom 1. Januar abweichen.",
  read: "Aus DATEV abrufen", download: "DATEV · JSON herunterladen", empty: "Abruf erfolgreich: keine Daten vorhanden.",
  count: "Abgerufene Datensätze", first: "Die ersten 50 Datensätze werden angezeigt. Der Download enthält das vollständige abgerufene Ergebnis.",
  details: "Datensatzfelder öffnen", history: "Übertragungsprotokoll", noHistory: "Noch keine Vorgänge.", success: "Erfolgreich", failed: "Fehlgeschlagen", started: "Gestartet",
  revokeLink: "Zugriff bei DATEV verwalten", busy: "Wird ausgeführt…", genericError: "Anfrage fehlgeschlagen. Verbindung prüfen und erneut versuchen.",
  connectLong: "DATEV · Langfristig verbinden", forceDisconnect: "DATEV · Ohne Bestätigung trennen",
  session: "DATEV-Anmeldung gültig bis", sessionHint: "Eine normale DATEV-Anmeldung gilt höchstens 11 Stunden, danach ist eine neue Anmeldung nötig. Der Langzeitzugriff (bis zu 2 Jahre) wird nur für ein geprüftes Unternehmen erteilt.",
  longTerm: "Langzeitzugriff", longTermFor: "Langzeitzugriff für Unternehmen", longTermNeedsCheck: "Die langfristige Verbindung ist nach einer erfolgreichen Zugriffsprüfung des Unternehmens aus dem Profil möglich: normal verbinden, „Zugriff prüfen“ ausführen, dann trennen.",
  forcedNotice: "Die Tokens wurden in GMed gelöscht, DATEV hat den Widerruf jedoch nicht bestätigt. Den App-Zugriff bei DATEV widerrufen (Link unten).",
};
export function liveError(code: string | undefined, de: boolean) {
  const errors: Record<string, [string,string]> = {
    datev_confirmation_required: ["Обновите статус и подтвердите операцию ещё раз: данные подтверждения неполные или устарели.", "Status aktualisieren und den Vorgang erneut bestätigen: Die Bestätigungsdaten fehlen oder sind veraltet."],
    datev_not_configured: ["Сначала сохраните ключи приложения DATEV.", "Zuerst die DATEV-App-Zugangsdaten speichern."],
    datev_storage_unavailable: ["Не удалось прочитать или сохранить состояние подключения. Повторите позже.", "Der Verbindungsstatus konnte nicht gelesen oder gespeichert werden. Später erneut versuchen."],
    datev_decryption_failed: ["Не удалось прочитать сохранённые ключи подключения. Обратитесь к администратору.", "Gespeicherte Zugangsdaten konnten nicht gelesen werden. Die Administration kontaktieren."],
    datev_protocol_error: ["DATEV вернул неожиданные данные. Результат не показан и не доступен для выгрузки. Повторите запрос или проверьте интеграцию.", "DATEV hat unerwartete Daten geliefert. Das Ergebnis wird nicht angezeigt oder zum Download freigegeben. Anfrage wiederholen oder Integration prüfen."],
    datev_client_mismatch: ["Компания или среда в ответе не совпадает с выбранной. Данные заблокированы; проверьте подключение.", "Unternehmen oder Umgebung im Ergebnis stimmt nicht mit der Auswahl überein. Die Daten sind gesperrt; Verbindung prüfen."],
    datev_configuration_invalid: ["Проверьте Client ID, Client Secret и выбранную среду.", "Client ID, Client Secret und die ausgewählte Umgebung prüfen."],
    datev_fiscal_year_invalid: ["Укажите действительную дату начала финансового года.", "Ein gültiges Anfangsdatum des Wirtschaftsjahres angeben."],
    datev_profile_required: ["Сохраните Beraternummer и Mandantennummer в профиле.", "Beraternummer und Mandantennummer im Profil speichern."],
    datev_scope_missing: ["Не предоставлены нужные права API. Проверьте подписки приложения и повторите подключение.", "Erforderliche API-Rechte fehlen. App-Abonnements prüfen und erneut verbinden."],
    datev_access_denied: ["Нет доступа к выбранной компании или данным. Проверьте права в DATEV.", "Kein Zugriff auf das Unternehmen oder seine Daten. DATEV-Berechtigungen prüfen."],
    datev_reconnect_required: ["Сессия DATEV недоступна. Отключите её и войдите повторно.", "DATEV-Sitzung nicht verfügbar. Verbindung trennen und erneut anmelden."],
    datev_connection_changed: ["Подключение или профиль компании изменились. Обновите статус, проверьте компанию и подтвердите действие заново.", "Verbindung oder Unternehmensprofil wurde geändert. Status aktualisieren, Unternehmen prüfen und den Vorgang erneut bestätigen."],
    datev_revocation_unconfirmed: ["Чтение заблокировано, но DATEV не подтвердил отзыв токенов. Повторите отключение или отзовите доступ в DATEV.", "Lesen ist gesperrt, der Token-Widerruf wurde von DATEV nicht bestätigt. Trennung wiederholen oder Zugriff bei DATEV widerrufen."],
    datev_check_required: ["Сначала проверьте доступ к компании из профиля обычным подключением, затем отключитесь и запросите длительный доступ.", "Zuerst den Zugriff auf das Unternehmen aus dem Profil mit einer normalen Verbindung prüfen, dann trennen und den Langzeitzugriff anfordern."],
    datev_company_bound: ["Длительный доступ выдан для другой компании. Отключите его и подключитесь заново для компании из профиля.", "Der Langzeitzugriff gilt für ein anderes Unternehmen. Trennen und für das Unternehmen aus dem Profil neu verbinden."],
    datev_request_rejected: ["DATEV отклонил запрос как некорректный. Подключение остаётся активным; проверьте номера компании и выбранный период.", "DATEV hat die Anfrage als ungültig abgelehnt. Die Verbindung bleibt aktiv; Unternehmensnummern und Zeitraum prüfen."],
    datev_unavailable: ["DATEV сейчас недоступен. Повторите позже.", "DATEV ist derzeit nicht erreichbar. Später erneut versuchen."],
    datev_unreachable: ["Не удалось связаться с DATEV. Повторите позже.", "DATEV konnte nicht erreicht werden. Später erneut versuchen."],
    datev_redirect_invalid: ["Нужен callback GMed: /api/v1/datev/oauth/callback. Production требует HTTPS-домен GMed.", "GMed-Callback erforderlich: /api/v1/datev/oauth/callback. Production erfordert eine HTTPS-Domain von GMed."],
    datev_rate_limited: ["DATEV ограничил частоту запросов. Повторите позже.", "DATEV-Anfragelimit erreicht. Später erneut versuchen."],
    datev_response_too_large: ["Ответ превышает лимит 8 MiB. Данные не показаны частично; нужен отдельный потоковый экспорт.", "Antwort überschreitet 8 MiB. Keine Teildaten angezeigt; ein separater Streaming-Export ist erforderlich."],
    datev_data_unavailable: ["Данные недоступны. Проверьте выбранный финансовый год и публикацию данных в DATEV.", "Daten nicht verfügbar. Wirtschaftsjahr und Bereitstellung in DATEV prüfen."],
  };
  return errors[code ?? ""]?.[de ? 1 : 0] ?? (de ? liveDe.genericError : liveRu.genericError);
}
