const descriptions = {
  connect: ["Откроется официальная страница DATEV для входа и разрешения доступа GMed. Бухгалтерские записи и платежи не создаются.", "Die offizielle DATEV-Seite wird zur Anmeldung und Freigabe für GMed geöffnet. Es werden keine Buchungen oder Zahlungen erstellt."],
  check: ["DATEV проверит доступ к указанной компании и вернёт список сервисов. Эта проверка не подтверждает доступ ко всем модулям и оригиналам счетов.", "DATEV prüft den Zugriff auf dieses Unternehmen und liefert seine Services. Dies bestätigt nicht den Zugriff auf alle Module oder Originalbelege."],
  disconnect: ["GMed заблокирует чтение и запросит у DATEV отзыв токенов доступа. Для следующего подключения потребуется новый вход. Если отзыв не подтверждён, это будет показано отдельно.", "GMed sperrt den Abruf und fordert bei DATEV den Token-Widerruf an. Danach ist eine neue Anmeldung nötig. Ein unbestätigter Widerruf wird ausdrücklich angezeigt."],
  connectLong: ["Откроется официальная страница DATEV. GMed запросит длительный доступ (до 2 лет) только к указанной компании; для другой компании потребуется новое подключение. Отозвать доступ можно здесь или на стороне DATEV. Бухгалтерские записи и платежи не создаются.", "Die offizielle DATEV-Seite wird geöffnet. GMed fordert einen Langzeitzugriff (bis zu 2 Jahre) nur für dieses Unternehmen an; für ein anderes Unternehmen ist eine neue Verbindung nötig. Der Zugriff kann hier oder bei DATEV widerrufen werden. Es werden keine Buchungen oder Zahlungen erstellt."],
  forceDisconnect: ["DATEV не подтвердил отзыв токенов. GMed удалит сохранённые токены без подтверждения, чтобы подключение можно было настроить заново. После этого обязательно отзовите доступ приложения на стороне DATEV.", "DATEV hat den Token-Widerruf nicht bestätigt. GMed löscht die gespeicherten Tokens ohne Bestätigung, damit die Verbindung neu eingerichtet werden kann. Danach den App-Zugriff unbedingt bei DATEV widerrufen."],
  refresh: ["GMed перечитает сохранённое состояние подключения и журнал. Запрос данных компании в DATEV не выполняется; текущий результат просмотра будет очищен.", "GMed lädt den gespeicherten Verbindungsstatus und das Protokoll neu. Es werden keine Unternehmensdaten bei DATEV abgefragt; das aktuelle Abrufresultat wird gelöscht."],
  save: ["Ключи приложения будут зашифрованы и сохранены на сервере GMed. Это ещё не авторизация DATEV. Секрет не выводится в подтверждении.", "Die App-Zugangsdaten werden verschlüsselt auf dem GMed-Server gespeichert. Dies ist noch keine DATEV-Autorisierung. Das Secret wird hier nicht angezeigt."],
  read: ["GMed запросит выбранные данные указанной компании из DATEV. Результат можно просмотреть и скачать; счета, проводки и платежи не создаются. Данные относятся к последнему архивированному состоянию DATEV.", "GMed ruft die ausgewählten Daten dieses Unternehmens aus DATEV ab. Das Ergebnis kann angesehen und heruntergeladen werden. Es entstehen keine Rechnungen, Buchungen oder Zahlungen. Die Daten stammen aus der letzten DATEV-Archivierung."],
  download: ["На компьютер будет скачан JSON со всеми записями текущего результата. Это выгрузка для просмотра, не файл отправки или импорта в DATEV. Внешний запрос не выполняется.", "Alle Datensätze des aktuellen Ergebnisses werden als JSON heruntergeladen. Dies ist ein Ansichtsexport, keine Übertragung oder Importdatei für DATEV. Es erfolgt keine externe Abfrage."],
  portal: ["В новой вкладке откроется официальный кабинет DATEV. Действия и разрешения в нём управляются отдельно; GMed не выполняет платёж и не изменяет данные автоматически.", "Das offizielle DATEV-Portal öffnet sich in einem neuen Tab. Aktionen und Berechtigungen werden dort separat verwaltet. GMed führt keine Zahlung aus und ändert keine Daten automatisch."],
  profile: ["Профиль компании и выбранные модули сохранятся только в GMed. Эти сведения не предоставляют прав DATEV; после изменения компании проверьте доступ повторно.", "Unternehmensprofil und ausgewählte Module werden nur in GMed gespeichert. Diese Angaben erteilen keine DATEV-Rechte. Nach einem Unternehmenswechsel den Zugriff erneut prüfen."],
  brief: ["На компьютер будет скачан список настроек и открытых вопросов для бухгалтерии. Ключи и токены в файл не включаются. Это не экспорт бухгалтерских данных в DATEV.", "Eine Checkliste mit Einstellungen und offenen Fragen für die Buchhaltung wird heruntergeladen. Schlüssel und Tokens sind nicht enthalten. Dies ist kein Rechnungswesenexport an DATEV."],
} as const;
export function operationDescription(operation: keyof typeof descriptions, de: boolean) {
  return descriptions[operation][de ? 1 : 0];
}
