import { useLang } from "@/lib/i18n";

const ru = {
  profile: "Профиль бухгалтерии", profileHint: "Сохраняется в GMed. Номера можно добавить позже; они не предоставляют доступ к DATEV.",
  companyName: "Название компании", consultant: "Beraternummer", client: "Mandantennummer",
  numbersHint: "Номер бухгалтерии и номер вашей компании в DATEV. Это не номер клиента GMed.",
  version: "Версия Belege online, если известна", versionPlaceholder: "Можно уточнить позже",
  modules: "Модули вашей бухгалтерии", modulesHint: "Отметьте используемые модули. Наличие модуля в кабинете не подтверждает доступ к его данным из GMed.",
  used: "Используется", accessPending: "Доступ в GMed не настроен",
  belege: "Оригиналы счетов и документы. В GMed уже работает импорт PDF/XML и проверка после распознавания. Автоматическое получение из DATEV требует отдельного доступа.",
  belegfreigabe: "Проверка и согласование счетов в DATEV. Получение статусов требует проверки интерфейса; согласование в GMed не меняет статус DATEV.",
  bank: "Банковские операции и остатки в DATEV. Способ получения данных в GMed нужно согласовать отдельно; платежи из GMed не выполняются.",
  kassenbuch: "Кассовые документы и движения. Доступ к кассовой книге нужно проверить отдельно; наличие бухгалтерских проводок не означает доступ к самой книге.",
  auswertungspakete: "Пакеты отчётов бухгалтерии. Export Rechnungswesen — кандидат для проводок и оборотно-сальдовых данных; получение готовых PDF-отчётов проверяется отдельно.",
  liquiditaetsmonitor: "Прогноз ликвидности в DATEV. Получение готового прогноза в GMed пока не подтверждено; банковские данные сами по себе его не заменяют.",
  next: "Следующие шаги", exportService: "DATEV Datenservice Export Rechnungswesen",
  exportHint: "Отдельный сервис для получения бухгалтерских данных. Укажите, что уже известно от бухгалтерии.",
  unknown: "Нужно уточнить", notOrdered: "Не заказан", ordered: "Заказан — по данным бухгалтерии",
  serviceUnverified: "Заказ сервиса и разрешение GMed проверяются отдельно после авторизации.",
  accessStep: "Приложение GMed в DATEV", accessStepHint: "Нужны регистрация приложения, разрешённые API и допуск к рабочим данным.",
  authStep: "Авторизация бухгалтерии", authStepHint: "После настройки приложения бухгалтерия предоставит доступ на официальной странице DATEV.",
  originalsStep: "Оригиналы инвойсов", originalsStepHint: "Уточнить версию Belege online и доступный способ получения PDF/XML.",
  openPortal: "Открыть кабинет DATEV", portalHint: "Официальная страница входа. Вход в кабинет не подключает GMed автоматически.",
  brief: "Скачать список для бухгалтерии", briefHint: "Файл на немецком с сохранённым профилем и вопросами по доступу.",
  docs: "О сервисе экспорта DATEV", save: "Сохранить профиль", saving: "Сохранение…", saved: "Профиль сохранён в GMed. Подключение к DATEV ещё не выполнено.",
  reset: "Отменить изменения", reload: "Загрузить заново", loadError: "Не удалось загрузить настройки DATEV. Повторите попытку.",
  saveError: "Не удалось сохранить профиль. Изменения остались в форме.", conflict: "Профиль изменён в другой сессии. Загрузите актуальную версию перед повторным сохранением.",
  invalidNumbers: "Укажите оба номера цифрами: Beraternummer — до 7, Mandantennummer — до 5. Или оставьте оба поля пустыми.",
  unsaved: "Есть несохранённые изменения", loading: "Загрузка настроек…", selectedModules: "Модулей в профиле", savedAt: "Профиль сохранён",
};
const de: typeof ru = {
  profile: "Buchhaltungsprofil", profileHint: "Wird in GMed gespeichert. Nummern können später ergänzt werden; sie erteilen keinen DATEV-Zugriff.",
  companyName: "Unternehmensname", consultant: "Beraternummer", client: "Mandantennummer",
  numbersHint: "Nummern der Steuerberatung und Ihres Unternehmens in DATEV. Keine GMed-Patientennummer.",
  version: "Version von Belege online, falls bekannt", versionPlaceholder: "Kann später geklärt werden",
  modules: "Module Ihrer Buchhaltung", modulesHint: "Genutzte Module auswählen. Ein Modul im DATEV-Portal bestätigt noch keinen Datenzugriff durch GMed.",
  used: "Wird genutzt", accessPending: "GMed-Zugriff nicht eingerichtet",
  belege: "Originalrechnungen und Belege. PDF/XML-Import und Prüfung nach der Erkennung sind in GMed verfügbar. Der automatische DATEV-Abruf benötigt einen separaten Zugang.",
  belegfreigabe: "Prüfung und Freigabe von Rechnungen in DATEV. Der Statusabruf muss geprüft werden; eine Prüfung in GMed ändert keinen DATEV-Freigabestatus.",
  bank: "Bankumsätze und Kontostände in DATEV. Der Datenabruf für GMed muss separat geklärt werden; GMed führt keine Zahlungen aus.",
  kassenbuch: "Kassenbelege und Bewegungen. Der Zugriff auf das Kassenbuch muss separat geprüft werden; Kontobuchungen sind kein Zugriff auf das Kassenbuch selbst.",
  auswertungspakete: "Auswertungspakete der Buchhaltung. Export Rechnungswesen kommt für Buchungen und Summen-/Saldendaten infrage; fertige PDF-Auswertungen müssen separat geprüft werden.",
  liquiditaetsmonitor: "Liquiditätsprognose in DATEV. Ein Abruf der fertigen Prognose durch GMed ist noch nicht bestätigt; Bankdaten allein ersetzen sie nicht.",
  next: "Nächste Schritte", exportService: "DATEV Datenservice Export Rechnungswesen",
  exportHint: "Separater Dienst zum Abruf von Rechnungswesendaten. Den bekannten Stand der Steuerberatung angeben.",
  unknown: "Noch zu klären", notOrdered: "Nicht bestellt", ordered: "Laut Steuerberatung bestellt",
  serviceUnverified: "Bestellung und Berechtigungen für GMed werden nach der Autorisierung separat geprüft.",
  accessStep: "GMed-App bei DATEV", accessStepHint: "App-Registrierung, freigegebene APIs und Zulassung für Produktivdaten werden benötigt.",
  authStep: "Autorisierung der Steuerberatung", authStepHint: "Nach Einrichtung der App erteilt die Steuerberatung den Zugriff auf der offiziellen DATEV-Seite.",
  originalsStep: "Originalrechnungen", originalsStepHint: "Belege-online-Version und möglichen Abruf von PDF/XML klären.",
  openPortal: "DATEV-Portal öffnen", portalHint: "Offizielle Anmeldeseite. Die Anmeldung im Portal verbindet GMed nicht automatisch.",
  brief: "Checkliste für die Steuerberatung", briefHint: "Deutsche Textdatei mit gespeichertem Profil und offenen Zugangsfragen.",
  docs: "Zum DATEV-Exportdienst", save: "Profil speichern", saving: "Wird gespeichert…", saved: "Profil in GMed gespeichert. Die DATEV-Verbindung ist noch nicht eingerichtet.",
  reset: "Änderungen verwerfen", reload: "Neu laden", loadError: "DATEV-Einstellungen konnten nicht geladen werden. Bitte erneut versuchen.",
  saveError: "Profil konnte nicht gespeichert werden. Die Änderungen bleiben im Formular.", conflict: "Das Profil wurde in einer anderen Sitzung geändert. Vor dem Speichern die aktuelle Version laden.",
  invalidNumbers: "Beide Nummern als Ziffern angeben: Beraternummer bis 7, Mandantennummer bis 5 Stellen. Oder beide Felder leer lassen.",
  unsaved: "Ungespeicherte Änderungen", loading: "Einstellungen werden geladen…", selectedModules: "Module im Profil", savedAt: "Profil gespeichert",
};
export function useDatevSetupText() {
  const { lang } = useLang();
  return lang === "de" ? de : ru;
}
