import { useLang } from "@/lib/i18n";

const ru = {
  invoices: "Счета GMed", fromDatev: "Из DATEV", connection: "Подключение DATEV",
  notConnected: "Не подключено", readOnly: "Только просмотр", demo: "Демо",
  live: "Данные DATEV", openDemo: "Открыть демо", demoCompany: "GMed Demo · тестовая компания",
  systemName: "DATEV Unternehmen online",
  connectionStatus: "Статус подключения", adminConnectionHint: "Подключение DATEV настраивает администратор.",
  connect: "Подключить DATEV", setupNeeded: "Подключение станет доступно после настройки доступа бухгалтерии.",
  company: "Компания DATEV", notSelected: "Не выбрана", lastSync: "Последнее получение данных", never: "Ещё не выполнялось",
  mode: "Режим работы", sending: "Отправка в DATEV", disabled: "Недоступна",
  prerequisites: "Для реального подключения", product: "Система DATEV", productHint: "DATEV Unternehmen online", selected: "Выбрано",
  documentVersion: "Версия Belege online", documentVersionHint: "Нужно уточнить версию кабинета бухгалтерии: от неё зависит доступный обмен документами.",
  access: "Доступ для GMed", accessHint: "Нужно зарегистрировать приложение и настроить разрешения на получение данных.",
  authorization: "Подтверждение бухгалтерии", authorizationHint: "Вход и предоставление доступа пройдут на официальной странице DATEV.",
  pending: "Ожидается", settings: "Настройки интеграции", integrations: "Интеграции", openInvoices: "Открыть счета DATEV",
  previewHint: "Пока доступ не настроен, можно посмотреть работу раздела на вымышленных счетах и клиентах.",
  disconnectedTitle: "Подключите бухгалтерию к GMed",
  disconnectedHint: "Для подключения выбрана DATEV Unternehmen online. Здесь появятся доступные данные после настройки прав; получение оригиналов счетов проверяется отдельно.",
  demoNotice: "Демонстрационные данные. Счета, клиенты и заказы вымышлены. Привязки действуют до перезагрузки страницы; реальные записи не создаются.",
  search: "Поиск по номеру, поставщику или клиенту", binding: "Привязка к клиенту", all: "Все счета", linked: "Привязан в демо", unlinked: "Без привязки",
  suggested: "Клиент найден", needsClient: "Выбрать клиента", number: "Номер счёта", supplier: "Поставщик", recipient: "Получатель", date: "Дата счёта", due: "Оплатить до", total: "Итого",
  count: "Счетов", linkedCount: "Привязано", needsReview: "Нужна проверка", totalAmount: "Сумма демо-счетов",
  empty: "Счета не найдены", emptyHint: "Попробуйте другой запрос или сбросьте фильтры.", clear: "Сбросить фильтры",
  reloadDemo: "Обновить демо", demoRefreshed: "Демо-примеры перечитаны. Связи сохранены; обращений к DATEV не было.",
  view: "Просмотреть", review: "Просмотр счёта DATEV", reviewHint: "Демонстрация просмотра документа и привязки внутри GMed.",
  original: "Образец документа", download: "Скачать демо-PDF", zoomOut: "Уменьшить", zoomIn: "Увеличить", fit: "По ширине",
  client: "Демо-клиент", order: "Демо-заказ", chooseClient: "Выберите клиента", chooseOrder: "Выберите заказ",
  autoHint: "Клиент определён по документу. Проверьте его и выберите заказ.", manualHint: "Совпадение не найдено. Выберите клиента вручную.",
  fields: "Реквизиты счёта", net: "Без НДС", vat: "НДС", currency: "Валюта", paymentStatus: "Статус оплаты", unavailable: "Нет данных",
  lines: "Позиции", showText: "Показать текст документа", hideText: "Скрыть текст документа",
  confirm: "Я проверил клиента и заказ по документу.", save: "Сохранить демо-привязку", saved: "Демо-привязка сохранена. Реальные записи не изменялись.",
  bindingNote: "Выбор клиента меняет только демо-привязку. Оригинал и реквизиты документа остаются доступными для сверки.",
  source: "Источник", sampleSource: "Локальный демонстрационный пример", sourceId: "ID документа",
  imageError: "Не удалось открыть предпросмотр. Скачайте демо-PDF для просмотра.",
};

const de: typeof ru = {
  invoices: "GMed-Rechnungen", fromDatev: "Aus DATEV", connection: "DATEV-Verbindung",
  notConnected: "Nicht verbunden", readOnly: "Nur lesen", demo: "Demo",
  live: "DATEV-Daten", openDemo: "Demo öffnen", demoCompany: "GMed Demo · Testunternehmen",
  systemName: "DATEV Unternehmen online",
  connectionStatus: "Verbindungsstatus", adminConnectionHint: "Die DATEV-Verbindung wird in der Administration eingerichtet.",
  connect: "DATEV verbinden", setupNeeded: "Die Verbindung wird nach Einrichtung des Buchhaltungszugangs verfügbar.",
  company: "DATEV-Mandant", notSelected: "Nicht ausgewählt", lastSync: "Letzter Datenabruf", never: "Noch nicht erfolgt",
  mode: "Betriebsmodus", sending: "An DATEV senden", disabled: "Nicht verfügbar",
  prerequisites: "Für die echte Verbindung", product: "DATEV-System", productHint: "DATEV Unternehmen online", selected: "Ausgewählt",
  documentVersion: "Version von Belege online", documentVersionHint: "Die Version der Buchhaltungsumgebung klären: Davon hängt der verfügbare Dokumentenaustausch ab.",
  access: "Zugang für GMed", accessHint: "Anwendung registrieren und Berechtigungen zum Datenabruf einrichten.",
  authorization: "Freigabe der Buchhaltung", authorizationHint: "Anmeldung und Freigabe erfolgen auf der offiziellen DATEV-Seite.",
  pending: "Ausstehend", settings: "Integrationseinstellungen", integrations: "Integrationen", openInvoices: "DATEV-Rechnungen öffnen",
  previewHint: "Bis der Zugang eingerichtet ist, lässt sich der Bereich mit fiktiven Rechnungen und Patienten testen.",
  disconnectedTitle: "Buchhaltung mit GMed verbinden",
  disconnectedHint: "DATEV Unternehmen online wurde ausgewählt. Nach Einrichtung der Berechtigungen erscheinen hier verfügbare Daten; der Abruf von Originalrechnungen wird separat geprüft.",
  demoNotice: "Demodaten. Rechnungen, Patienten und Aufträge sind fiktiv. Zuordnungen gelten bis zum Neuladen der Seite; es werden keine echten Datensätze erstellt.",
  search: "Nach Nummer, Lieferant oder Patient suchen", binding: "Patientenzuordnung", all: "Alle Rechnungen", linked: "In Demo zugeordnet", unlinked: "Nicht zugeordnet",
  suggested: "Patient gefunden", needsClient: "Patient auswählen", number: "Rechnungsnummer", supplier: "Lieferant", recipient: "Empfänger", date: "Rechnungsdatum", due: "Fällig am", total: "Bruttobetrag",
  count: "Rechnungen", linkedCount: "Zugeordnet", needsReview: "Zu prüfen", totalAmount: "Summe der Demorechnungen",
  empty: "Keine Rechnungen gefunden", emptyHint: "Andere Suche versuchen oder Filter zurücksetzen.", clear: "Filter zurücksetzen",
  reloadDemo: "Demo aktualisieren", demoRefreshed: "Demobeispiele neu geladen. Zuordnungen bleiben erhalten; keine DATEV-Abfrage erfolgt.",
  view: "Ansehen", review: "DATEV-Rechnung ansehen", reviewHint: "Demonstration der Dokumentansicht und Zuordnung innerhalb von GMed.",
  original: "Musterdokument", download: "Demo-PDF herunterladen", zoomOut: "Verkleinern", zoomIn: "Vergrößern", fit: "An Breite anpassen",
  client: "Demo-Patient", order: "Demo-Auftrag", chooseClient: "Patient auswählen", chooseOrder: "Auftrag auswählen",
  autoHint: "Patient anhand des Dokuments erkannt. Bitte prüfen und Auftrag auswählen.", manualHint: "Keine Übereinstimmung gefunden. Patienten manuell auswählen.",
  fields: "Rechnungsangaben", net: "Nettobetrag", vat: "Umsatzsteuer", currency: "Währung", paymentStatus: "Zahlungsstatus", unavailable: "Keine Daten",
  lines: "Positionen", showText: "Dokumenttext anzeigen", hideText: "Dokumenttext ausblenden",
  confirm: "Ich habe Patient und Auftrag anhand des Dokuments geprüft.", save: "Demo-Zuordnung speichern", saved: "Demo-Zuordnung gespeichert. Echte Datensätze wurden nicht geändert.",
  bindingNote: "Die Auswahl ändert nur die Demo-Zuordnung. Original und Rechnungsangaben bleiben zum Abgleich verfügbar.",
  source: "Quelle", sampleSource: "Lokales Demonstrationsbeispiel", sourceId: "Dokument-ID",
  imageError: "Vorschau konnte nicht geöffnet werden. Bitte das Demo-PDF herunterladen.",
};

export function useDatevText() {
  const { lang } = useLang();
  return { text: lang === "de" ? de : ru, lang };
}
